// CELPIP Question Bank - Parts 4-6 (3 sets each)

const PART4_SETS = [
  { // Set A
    title: "Listening to a News Item",
    time: 300,
    desc: "You will hear a news report. Listen carefully and answer the questions that follow.",
    script: "Good evening. A new community composting initiative is being launched in the city of Maplewood this spring, and organizers say it could divert up to thirty percent of the city's organic waste from landfills within its first year. The program, called 'Green Bins for Maplewood,' will distribute free composting bins to every household in the city beginning April first. Residents will be able to place food scraps, yard waste, and biodegradable materials in the bins, which will be collected every two weeks by municipal crews.\n\nThe initiative was spearheaded by city councillor Diane Okoro, who says she was inspired after visiting a similar program in the city of Guelph that reduced landfill waste by twenty-two percent in just eight months. 'We produce an enormous amount of organic waste that doesn't need to end up in a landfill,' Councillor Okoro said at a press conference yesterday. 'Composting is one of the most effective and affordable ways for a municipality to reduce its environmental footprint.'\n\nThe program will cost the city an estimated one point two million dollars in its first year, funded through a reallocation of the existing waste management budget. Critics, however, argue that the money would be better spent on upgrading the city's aging recycling infrastructure, which has seen processing delays of up to three weeks in recent months. Despite the debate, a recent survey showed that sixty-eight percent of Maplewood residents support the composting program.",
    questions: [
      { q: "What is the news report mainly about?", opts: ["A new recycling plant opening in Maplewood.", "A community composting program launching in Maplewood.", "A debate about closing a local landfill.", "A fine imposed on residents for improper waste disposal."], ans: 1 },
      { q: "How often will the composting bins be collected?", opts: ["Once a week.", "Every two weeks.", "Once a month.", "Twice a week."], ans: 1 },
      { q: "What inspired Councillor Okoro to propose the program?", opts: ["A visit to a similar program in Guelph.", "A request from a group of environmental activists.", "A federal government grant opportunity.", "A report about rising landfill costs."], ans: 0 },
      { q: "How much will the program cost in its first year?", opts: ["Eight hundred thousand dollars.", "One million dollars.", "One point two million dollars.", "One point five million dollars."], ans: 2 },
      { q: "What do critics of the program believe?", opts: ["Composting is not effective at reducing waste.", "The money should be used to upgrade recycling infrastructure.", "The collection schedule is not frequent enough.", "Residents should pay for their own composting bins."], ans: 1 }
    ]
  },
  { // Set B
    title: "Listening to a News Item",
    time: 300,
    desc: "You will hear a news report. Listen carefully and answer the questions that follow.",
    script: "This is CTV Barrie News. The town of Clearwater is celebrating the completion of the Lakeshore Heritage Trail, a twelve-kilometer multi-use pathway that connects the downtown waterfront district to the Pinewood Nature Reserve on the town's eastern boundary. The trail, which took three years and fourteen million dollars to complete, officially opens to the public this Saturday.\n\nMayor Richard Tran called the trail 'a transformative project for Clearwater' at a ribbon-cutting ceremony held earlier today. The pathway features separated lanes for cyclists and pedestrians, six rest stations with benches and water fountains, and three lookout points offering panoramic views of Lake Simcoe. Accessibility was a key priority in the design — all surfaces are wheelchair-friendly, and audio-guided information posts are available at historical landmarks along the route.\n\nThe trail is expected to boost local tourism significantly. According to the town's economic development office, a comparable trail in Collingwood generated approximately four million dollars in tourism revenue within its first two years. Local business owners near the trail have already reported increased interest, with two new cafés and a bike rental shop opening in anticipation of the trail's launch.\n\nEnvironmental groups have praised the project for preserving existing green spaces rather than paving over them. Ninety-two percent of the trail follows the natural shoreline and existing parkland, minimizing ecological disruption.",
    questions: [
      { q: "How long is the Lakeshore Heritage Trail?", opts: ["Eight kilometers.", "Ten kilometers.", "Twelve kilometers.", "Fifteen kilometers."], ans: 2 },
      { q: "How much did the trail cost to complete?", opts: ["Eight million dollars.", "Ten million dollars.", "Twelve million dollars.", "Fourteen million dollars."], ans: 3 },
      { q: "What accessibility feature does the trail include?", opts: ["Electric shuttle buses along the route.", "Audio-guided information posts at landmarks.", "Free wheelchair rentals at the entrance.", "Guide dogs available at rest stations."], ans: 1 },
      { q: "What economic impact is expected from the trail?", opts: ["It will create two hundred new jobs immediately.", "Property values will decrease near the trail.", "Tourism revenue comparable to Collingwood's trail success.", "The town will charge admission to cover costs."], ans: 2 },
      { q: "Why have environmental groups praised the project?", opts: ["It plants ten thousand new trees along the route.", "It runs entirely on solar-powered infrastructure.", "It preserves existing green spaces and follows the natural shoreline.", "It bans motorized vehicles in the entire downtown area."], ans: 2 }
    ]
  },
  { // Set C
    title: "Listening to a News Item",
    time: 300,
    desc: "You will hear a news report. Listen carefully and answer the questions that follow.",
    script: "Good morning from CBC Radio One. The city of Brampton is launching an innovative pilot program aimed at reducing traffic congestion and carbon emissions in one of Ontario's fastest-growing municipalities. Starting May first, the city will offer free public transit for all residents during off-peak hours — that's between ten AM and three PM on weekdays, and all day on weekends.\n\nThe program, called 'FreeRide Brampton,' will run for a six-month trial period. City officials estimate it will cost approximately three point five million dollars, funded through a combination of provincial transit grants and municipal reserves. During a press briefing yesterday, transit director Angela Chu stated that the goal is to increase bus ridership by at least twenty-five percent during off-peak periods, which currently run at only forty percent capacity.\n\n'We have buses running routes with very few passengers during the middle of the day,' Director Chu explained. 'By removing the fare barrier, we hope to attract residents who might otherwise drive alone, which reduces congestion and emissions simultaneously.'\n\nResidents have shown strong interest. An online registration portal launched last week has already received over nine thousand sign-ups. However, the local taxi and ride-share industry has voiced concerns, arguing that free transit could undercut their businesses. The city has committed to monitoring the impact on private transportation providers and will publish a full report at the end of the trial.",
    questions: [
      { q: "What is the FreeRide Brampton program?", opts: ["Free bicycle rentals at transit stations.", "Free public transit during off-peak hours.", "Discounted ride-sharing during rush hours.", "Free parking at city-owned lots."], ans: 1 },
      { q: "How long will the pilot program run?", opts: ["Three months.", "Six months.", "Nine months.", "One year."], ans: 1 },
      { q: "What is the ridership goal?", opts: ["To increase peak-hour ridership by fifty percent.", "To increase off-peak ridership by twenty-five percent.", "To double weekend ridership.", "To fill all buses to maximum capacity."], ans: 1 },
      { q: "How many people have already signed up?", opts: ["About three thousand.", "About five thousand.", "About nine thousand.", "About twelve thousand."], ans: 2 },
      { q: "Who has expressed concerns about the program?", opts: ["Environmental advocacy groups.", "The provincial government.", "The taxi and ride-share industry.", "Neighbouring municipalities."], ans: 2 }
    ]
  }
];

const PART5_SETS = [
  { // Set A
    title: "Listening to a Discussion",
    time: 360,
    desc: "You will hear a discussion between three people. Listen carefully and answer the questions.",
    videoScene: "<h4>🎬 Video Scene Description</h4><p>Three colleagues — Aisha, Ben, and Carmen — are seated around a modern oval conference table in a brightly lit office meeting room. A large screen behind them shows a project timeline with the title 'Q3 Product Launch Plan.' Each person has a laptop open and a coffee mug on the table. Aisha is at the head of the table with printed notes in front of her.</p>",
    script: "Aisha: Okay, let's get started. We need to finalize our strategy for the Q3 product launch. We're about ten weeks out, and there are still some major decisions to make. Ben, can you give us an update on the marketing side?\n\nBen: Sure. So we've, um, confirmed the social media campaign — we're running targeted ads on Instagram, Facebook, and LinkedIn starting six weeks before launch. The budget for digital ads is forty thousand dollars, and we've reserved another fifteen thousand for influencer partnerships. My concern right now is the landing page. Our web team is behind schedule, and I'm worried it won't be ready in time for the pre-launch teaser.\n\nAisha: How far behind are they?\n\nBen: About two weeks. They say the delay is because of the new design system migration. I've escalated it, but I might need your help pushing it with the VP of engineering.\n\nCarmen: Can I jump in? On the sales side, I've been getting a lot of questions from our retail partners about pricing and availability. We originally said mid-July for the retail launch, but if the landing page is delayed, should we also push back the retail date?\n\nAisha: That's a good point. I don't think we should push back the retail date, though. The landing page primarily supports direct-to-consumer sales. Retail can proceed on its own timeline. Ben, do you agree?\n\nBen: Yeah, I think that's right. The retail partners have their own promotional materials. The landing page delay only affects our online channel.\n\nCarmen: Okay, that makes sense. One more thing — I've negotiated an exclusive two-week window with our largest retailer, ValueMart, where they'll be the only brick-and-mortar store carrying the product. In exchange, they've committed to featuring it in their weekly flyer and giving us end-cap displays in two hundred locations.\n\nAisha: That's fantastic, Carmen. Two hundred locations is huge visibility. Let's make sure we have enough inventory to support that. Ben, the influencer content should ideally go live the same week as the ValueMart launch to create maximum buzz.\n\nBen: Agreed. I'll coordinate the timing with the influencer agency.",
    questions: [
      { q: "How far away is the product launch?", opts: ["About six weeks.", "About eight weeks.", "About ten weeks.", "About twelve weeks."], ans: 2 },
      { q: "What is Ben's main concern?", opts: ["The social media ads are too expensive.", "The landing page may not be ready in time.", "The influencers are not well-known enough.", "The marketing budget has been cut."], ans: 1 },
      { q: "Why is the web team behind schedule?", opts: ["They lost two developers last month.", "They are working on a design system migration.", "The project requirements changed unexpectedly.", "They are waiting for content from marketing."], ans: 1 },
      { q: "What does Aisha decide about the retail launch date?", opts: ["It should be pushed back by two weeks.", "It should proceed as planned.", "It should be moved earlier to compensate.", "It should be cancelled entirely."], ans: 1 },
      { q: "What did Carmen negotiate with ValueMart?", opts: ["A permanent shelf space contract.", "A twenty percent discount on wholesale pricing.", "An exclusive two-week window with prominent displays.", "Free advertising in their national campaigns."], ans: 2 },
      { q: "How many store locations will feature the product?", opts: ["Fifty.", "One hundred.", "One hundred and fifty.", "Two hundred."], ans: 3 },
      { q: "What does Aisha suggest about the influencer content timing?", opts: ["It should launch a month before the product.", "It should go live the same week as the ValueMart launch.", "It should only run on weekends.", "It should be postponed until after launch reviews come in."], ans: 1 },
      { q: "What is Ben's role in the project?", opts: ["He manages the sales team.", "He handles the marketing and digital campaigns.", "He oversees product development.", "He coordinates logistics and shipping."], ans: 1 }
    ]
  },
  { // Set B
    title: "Listening to a Discussion",
    time: 360,
    desc: "You will hear a discussion between three people. Listen carefully and answer the questions.",
    videoScene: "<h4>🎬 Video Scene Description</h4><p>Three university students — David, Fatima, and Grace — are sitting at a round table in a campus library study room. Books and tablets are spread across the table. A whiteboard behind them shows 'Group Project: Urban Sustainability Report — Due April 18.' David has a pen in hand, doodling on his notepad. Fatima is looking at her laptop screen. Grace is flipping through a printed article.</p>",
    script: "David: Alright, so we need to figure out how we're splitting up the sustainability report. It's due in three weeks and we haven't even started the research phase.\n\nFatima: I've actually, um, already done some preliminary research on green building certifications — like LEED and BREEAM. I found some great case studies from Vancouver and Toronto that we could use.\n\nGrace: That's awesome, Fatima. I was thinking I could focus on urban transportation — specifically, how cities are transitioning to electric bus fleets and expanding bike-sharing programs. There's a lot of recent data from Montreal we could reference.\n\nDavid: Okay, that leaves me with... what? Waste management and water conservation?\n\nFatima: That could work perfectly. You could look at Calgary's zero-waste strategy and the rainwater harvesting systems they're testing in some Vancouver neighbourhoods.\n\nDavid: Fine, I'll take those two. Now, how are we structuring the report? The prof said it needs to be at least twenty-five pages with a minimum of fifteen academic sources.\n\nGrace: I think we should have an introduction, three main sections — one for each of our topics — a comparative analysis section, and a conclusion with recommendations. Each main section should be about six to seven pages.\n\nFatima: That sounds solid. For the comparative analysis, we could create a table comparing the three cities across all our topics. Visual representations always get bonus marks.\n\nDavid: Good idea. What about the presentation? She said it's worth thirty percent of the grade.\n\nGrace: I think we should use Canva or Google Slides and keep it visual — lots of infographics and minimal text on slides. We each present our own section, and then one of us does the conclusion. I'd volunteer for the conclusion since I'm, uh, comfortable with public speaking.\n\nDavid: Works for me. Let's set a deadline for the first drafts — how about ten days from now, so we have time to review and edit each other's work?\n\nFatima: Ten days is tight, but doable. Let's also meet again next Wednesday to check in on progress.",
    questions: [
      { q: "How many weeks do they have until the report is due?", opts: ["Two weeks.", "Three weeks.", "Four weeks.", "Five weeks."], ans: 1 },
      { q: "What topic is Fatima covering?", opts: ["Urban transportation systems.", "Green building certifications.", "Waste management and water conservation.", "Renewable energy strategies."], ans: 1 },
      { q: "Which city does Grace mention for transportation data?", opts: ["Vancouver.", "Toronto.", "Calgary.", "Montreal."], ans: 3 },
      { q: "How long must the report be?", opts: ["At least fifteen pages.", "At least twenty pages.", "At least twenty-five pages.", "At least thirty pages."], ans: 2 },
      { q: "What does Fatima suggest for the comparative analysis?", opts: ["A written summary paragraph.", "A comparison table across three cities.", "An interview with a sustainability expert.", "A video documentary presentation."], ans: 1 },
      { q: "What percentage of the grade is the presentation worth?", opts: ["Twenty percent.", "Twenty-five percent.", "Thirty percent.", "Thirty-five percent."], ans: 2 },
      { q: "Who volunteers to present the conclusion?", opts: ["David.", "Fatima.", "Grace.", "They haven't decided yet."], ans: 2 },
      { q: "When is the deadline for first drafts?", opts: ["Five days from now.", "One week from now.", "Ten days from now.", "Two weeks from now."], ans: 2 }
    ]
  },
  { // Set C
    title: "Listening to a Discussion",
    time: 360,
    desc: "You will hear a discussion between three people. Listen carefully and answer the questions.",
    videoScene: "<h4>🎬 Video Scene Description</h4><p>Three coworkers — Raj, Sophia, and Tyler — are standing around a high-top table in a modern open-plan office. Behind them, a large window shows a city skyline at midday. Each has a tablet or phone in hand. A poster on the wall reads 'Customer Satisfaction Week.' Raj is gesturing expressively while speaking.</p>",
    script: "Raj: So, the customer satisfaction survey results are in, and honestly, they're a mixed bag. Overall satisfaction dropped from eighty-two percent last quarter to seventy-six percent this quarter. We need to figure out why and what we're going to do about it.\n\nSophia: I looked at the breakdown. The biggest drops were in two areas: response time and issue resolution. Customers said they're waiting an average of four minutes on hold before speaking to an agent, up from two minutes last quarter. And about thirty percent said their issue wasn't fully resolved on the first call.\n\nTyler: Those numbers are concerning. On the response time side, I think the issue is staffing. We lost three agents last month and haven't replaced them yet. The remaining team is stretched thin, especially during the eleven AM to two PM rush.\n\nRaj: I agree we need to hire, but that takes time. What can we do, um, in the short term to bring that hold time down?\n\nSophia: We could implement a callback system. Instead of waiting on hold, customers leave their number, and an agent calls them back within a specified window — say, thirty minutes. It's a better experience, and it reduces the pressure on the live queue.\n\nTyler: I like that idea. For the resolution issue, I think we need better training materials. A lot of the newer agents don't know how to handle complex cases, so they either escalate unnecessarily or give incomplete answers.\n\nRaj: Fair point. Let's create a knowledge base — a searchable database with step-by-step solutions for the fifty most common issues. That way, agents can quickly find accurate answers during a call.\n\nSophia: That's a great idea, Raj. I can start compiling the top issues from our ticket system. Tyler, could you work with the training team on updating the onboarding curriculum?\n\nTyler: Absolutely. I'll set up a meeting with them this week.\n\nRaj: Perfect. Let's aim to have both the callback system and the knowledge base in place within four weeks. I want to see those numbers back above eighty percent by next quarter.",
    questions: [
      { q: "What is the current overall satisfaction rate?", opts: ["Seventy percent.", "Seventy-six percent.", "Eighty-two percent.", "Eighty-five percent."], ans: 1 },
      { q: "What are the two main areas where scores dropped?", opts: ["Product quality and pricing.", "Response time and issue resolution.", "Website usability and delivery speed.", "Agent friendliness and technical knowledge."], ans: 1 },
      { q: "What is the average hold time now?", opts: ["Two minutes.", "Three minutes.", "Four minutes.", "Five minutes."], ans: 2 },
      { q: "Why does Tyler think response time has increased?", opts: ["The phone system was recently upgraded.", "Call volumes have unexpectedly doubled.", "Three agents left and haven't been replaced.", "Agents are spending too long on each call."], ans: 2 },
      { q: "What short-term solution does Sophia suggest?", opts: ["Hire temporary staff from an agency.", "Implement a customer callback system.", "Reduce operating hours to focus on quality.", "Add a self-service chatbot on the website."], ans: 1 },
      { q: "What does Raj propose for the resolution problem?", opts: ["Fire underperforming agents.", "Create a searchable knowledge base.", "Outsource complex cases to a specialist team.", "Require customers to submit issues by email only."], ans: 1 },
      { q: "What task does Tyler agree to take on?", opts: ["Compiling the top issues from the ticket system.", "Meeting with the training team about onboarding.", "Building the callback system software.", "Presenting the results to upper management."], ans: 1 },
      { q: "What is Raj's target satisfaction rate for next quarter?", opts: ["Above seventy-five percent.", "Above seventy-eight percent.", "Above eighty percent.", "Above eighty-five percent."], ans: 2 }
    ]
  }
];

const PART6_SETS = [
  { // Set A
    title: "Listening for Viewpoints",
    time: 480,
    desc: "You will hear a speaker presenting different viewpoints on a topic. Listen carefully and answer the questions.",
    script: "Today, I'd like to explore a topic that's generating significant debate in cities across Canada: the question of whether municipalities should ban single-use plastics, or whether the focus should instead be on improving recycling infrastructure.\n\nProponents of an outright ban argue that single-use plastics — things like straws, bags, cutlery, and takeout containers — are fundamentally wasteful. They point out that despite decades of recycling campaigns, only about nine percent of plastic ever produced globally has actually been recycled. The rest ends up in landfills, oceans, or is incinerated. Supporters of a ban say that recycling, um, creates a false sense of environmental responsibility. People feel good about tossing a plastic container into the blue bin, but the reality is that much of it never gets processed. A ban, they argue, would force businesses and consumers to adopt genuinely sustainable alternatives — like compostable containers, reusable bags, and paper-based packaging.\n\nOn the other hand, opponents of a ban raise several practical concerns. First, they argue that alternatives to plastic aren't always more environmentally friendly. Paper bags, for example, require significantly more water and energy to produce than plastic bags. Compostable containers often only break down in industrial composting facilities, which many municipalities don't have. If these items end up in a regular landfill, they decompose no faster than conventional plastics.\n\nSecondly, small business owners worry about the financial impact. A restaurant that switches from plastic to compostable takeout containers might see its packaging costs increase by forty to sixty percent. For a small business already operating on thin margins, that's a significant burden.\n\nA third perspective — and one that's gaining traction — is a hybrid approach. Under this model, municipalities would ban the most problematic single-use items, like plastic straws and polystyrene foam, while simultaneously investing in better recycling and composting infrastructure. This approach acknowledges that plastic, when properly recycled, can have a lower environmental impact than some alternatives, while still addressing the most harmful products that rarely get recycled.\n\nUltimately, whatever path cities choose, experts agree that public education is the critical missing piece. Without widespread understanding of what can and cannot be recycled — and why it matters — any policy will fall short of its goals.",
    questions: [
      { q: "What percentage of plastic produced globally has been recycled?", opts: ["About five percent.", "About nine percent.", "About fifteen percent.", "About twenty percent."], ans: 1 },
      { q: "According to ban supporters, what does recycling create?", opts: ["A profitable industry for municipalities.", "A false sense of environmental responsibility.", "New jobs in the manufacturing sector.", "Higher taxes for property owners."], ans: 1 },
      { q: "What concern do opponents raise about paper bags?", opts: ["They are too small for most shopping needs.", "They cannot be recycled at all.", "They require more water and energy to produce.", "They contain harmful chemicals."], ans: 2 },
      { q: "By how much could packaging costs increase for small businesses?", opts: ["Ten to twenty percent.", "Twenty to thirty percent.", "Forty to sixty percent.", "Seventy to ninety percent."], ans: 2 },
      { q: "What does the hybrid approach propose?", opts: ["Ban all plastics and switch entirely to paper.", "Ban the most harmful items while improving recycling infrastructure.", "Let the free market decide without government intervention.", "Tax plastic products and use revenue for environmental cleanup."], ans: 1 },
      { q: "What do experts say is the critical missing piece?", opts: ["Stricter law enforcement.", "International trade agreements.", "Public education about recycling.", "Higher taxes on plastic manufacturers."], ans: 2 }
    ]
  },
  { // Set B
    title: "Listening for Viewpoints",
    time: 480,
    desc: "You will hear a speaker presenting different viewpoints on a topic. Listen carefully and answer the questions.",
    script: "Remote work has become one of the most hotly debated topics in the modern workplace since the pandemic fundamentally changed how we think about where we work. Today, I want to examine the different perspectives on whether companies should embrace permanent remote work or require employees to return to the office.\n\nAdvocates of remote work point to several compelling benefits. Studies have consistently shown that remote workers report higher job satisfaction — one major survey found that seventy-eight percent of remote employees said they were happier compared to their in-office days. Productivity research also supports this view: a Stanford study of over sixteen thousand workers found a thirteen percent increase in productivity among those who worked from home. Remote work also expands the talent pool for employers. A company in Halifax can now hire a software developer in, um, Kelowna or Winnipeg without requiring relocation.\n\nHowever, critics of full-time remote work raise important counterpoints. They argue that collaboration and innovation suffer when teams aren't physically together. Spontaneous hallway conversations, whiteboard brainstorming sessions, and informal mentoring relationships are difficult to replicate over video calls. Some research suggests that while individual productivity on defined tasks increases remotely, creative problem-solving and complex team projects actually decline by up to twenty percent.\n\nThere's also the issue of employee well-being. While some employees thrive remotely, others report feeling isolated, disconnected from company culture, and struggle with work-life boundaries. Junior employees, in particular, may miss out on the observational learning that happens naturally in an office environment — watching how senior colleagues handle client calls, navigate office politics, or present ideas in meetings.\n\nA growing number of companies are adopting a hybrid model as a middle ground. Under this arrangement, employees typically come into the office two or three days a week for meetings and collaborative work, and spend the remaining days working remotely. Proponents of the hybrid model say it combines the best of both worlds: the flexibility and focus time of remote work with the social connection and collaboration benefits of in-person interaction.\n\nCritics of the hybrid model, however, call it the worst of both worlds. They argue it creates scheduling headaches, underutilizes expensive office space, and results in a two-tier culture where in-office employees get more face time with leadership and, consequently, more career advancement opportunities.",
    questions: [
      { q: "What percentage of remote employees reported higher happiness?", opts: ["Sixty-five percent.", "Seventy percent.", "Seventy-eight percent.", "Eighty-five percent."], ans: 2 },
      { q: "What did the Stanford study find about remote work productivity?", opts: ["A five percent decrease.", "No significant change.", "A thirteen percent increase.", "A twenty percent increase."], ans: 2 },
      { q: "According to critics, what declines in remote work settings?", opts: ["Employee retention rates.", "Individual task completion speed.", "Creative problem-solving and complex team projects.", "Compliance with company policies."], ans: 2 },
      { q: "Who may be most disadvantaged by remote work?", opts: ["Senior executives.", "Part-time workers.", "Junior employees.", "Technical specialists."], ans: 2 },
      { q: "What is the typical hybrid model schedule?", opts: ["One day in office, four days remote.", "Two or three days in office per week.", "Alternating weeks in office and remote.", "Full-time office with one remote day."], ans: 1 },
      { q: "What do critics say about the hybrid model?", opts: ["It is too expensive to implement.", "It can create a two-tier culture and scheduling problems.", "It violates employment standards legislation.", "It is only suitable for large corporations."], ans: 1 }
    ]
  },
  { // Set C
    title: "Listening for Viewpoints",
    time: 480,
    desc: "You will hear a speaker presenting different viewpoints on a topic. Listen carefully and answer the questions.",
    script: "The debate over whether to introduce congestion pricing in major Canadian cities has intensified in recent years, and today I want to present the various perspectives on this increasingly relevant issue.\n\nCongestion pricing is a system where drivers are charged a fee to enter designated high-traffic zones during peak hours. Cities like London, Stockholm, and Singapore have implemented versions of this approach with, supporters say, remarkable success. London, for example, saw a thirty percent reduction in traffic within the congestion zone after introducing its charge in 2003, and Stockholm reported a twenty-two percent decrease.\n\nAdvocates argue that congestion pricing is the most effective tool for reducing urban gridlock. They point out that the average Canadian commuter spends thirty-two minutes each way commuting, and in cities like Toronto and Vancouver, this figure can exceed an hour. The economic cost of congestion across Canada is estimated at approximately three point three billion dollars annually in lost productivity. By making driving during peak hours more expensive, proponents say, you incentivize people to carpool, take public transit, shift their hours, or work from home.\n\nOpponents, however, raise serious equity concerns. They argue that congestion pricing is essentially a regressive tax — it affects lower-income workers disproportionately, especially those in service industries who must commute during peak hours and cannot work remotely. A janitor or a retail worker doesn't have the luxury of, um, adjusting their schedule or working from home. If the daily charge is fifteen dollars each way, that's over six thousand dollars a year — a significant financial burden for someone earning minimum wage.\n\nThere's also skepticism about whether the revenue generated would actually be reinvested in public transit, as proponents promise. Critics point to historical examples where dedicated transportation funds were redirected to general government spending.\n\nA nuanced position suggests that congestion pricing could work, but only if it's paired with substantial improvements to public transit first. You can't charge people to drive if you don't offer them a viable alternative. This means more frequent bus and rail service, expanded routes to underserved areas, and reduced fares — all of which require significant upfront investment before a congestion charge would be fair to implement.",
    questions: [
      { q: "What is congestion pricing?", opts: ["A tax on fuel purchases in urban areas.", "A fee charged to drivers entering high-traffic zones during peak hours.", "A system of tolls on all major highways.", "A fine for driving over the speed limit in cities."], ans: 1 },
      { q: "By how much did London reduce traffic with congestion pricing?", opts: ["Fifteen percent.", "Twenty-two percent.", "Thirty percent.", "Forty percent."], ans: 2 },
      { q: "What is the estimated annual cost of congestion in Canada?", opts: ["About one billion dollars.", "About two billion dollars.", "About three point three billion dollars.", "About five billion dollars."], ans: 2 },
      { q: "Why do opponents call congestion pricing a 'regressive tax'?", opts: ["It gives tax breaks to wealthy corporations.", "It disproportionately burdens lower-income workers.", "It reduces government revenue from fuel taxes.", "It penalizes people who live in rural areas."], ans: 1 },
      { q: "What is a major concern about the revenue raised?", opts: ["It may not cover the cost of the program.", "It could be redirected away from transit.", "It would go to private companies, not the government.", "It would cause ticket prices to increase."], ans: 1 },
      { q: "What condition does the nuanced position say must be met first?", opts: ["Congestion must reach a critical threshold.", "Voter approval through a public referendum.", "Substantial improvements to public transit.", "Agreement from all neighbouring municipalities."], ans: 2 }
    ]
  }
];
