// CELPIP Question Bank - Parts 4-6 (3 sets each)

const PART4_SETS = [
  { // Set A
    title: "Listening to a News Item",
    time: 300,
    desc: "You will hear a news report. Listen carefully and answer the questions that follow.",
    script: "Good evening. A new community composting initiative is being launched in the city of Maplewood this spring, and organizers say it could divert up to thirty percent of the city's organic waste from landfills within its first year. The program, called 'Green Bins for Maplewood,' will distribute free composting bins to every household in the city beginning April first. Residents will be able to place food scraps, yard waste, and biodegradable materials in the bins, which will be collected every two weeks by municipal crews.\n\nThe initiative was spearheaded by city councillor Diane Okoro, who says she was inspired after visiting a similar program in the city of Guelph that reduced landfill waste by twenty-two percent in just eight months. 'We produce an enormous amount of organic waste that doesn't need to end up in a landfill,' Councillor Okoro said at a press conference yesterday. 'Composting is one of the most effective and affordable ways for a municipality to reduce its environmental footprint.'\n\nThe program will cost the city an estimated one point two million dollars in its first year, funded through a reallocation of the existing waste management budget. Critics, however, argue that the money would be better spent on upgrading the city's aging recycling infrastructure, which has seen processing delays of up to three weeks in recent months. Despite the debate, a recent survey showed that sixty-eight percent of Maplewood residents support the composting program.",
    questions: [
      { q: "What is the news report mainly about?", opts: ["A new recycling plant opening in Maplewood.", "A community composting program launching in Maplewood.", "A debate about closing a local landfill.", "A fine imposed on residents for improper waste disposal."], ans: 1 },
      { q: "How often will the composting bins be collected?", opts: ["Once a week.", "Every two weeks.", "Once a month.", "Twice a week."], ans: 1 },
      { q: "What inspired Councillor Okoro to propose the program?", opts: ["A visit to a similar program in Guelph.", "A request from a group of environmental activists.", "A federal government grant opportunity.", "A report about rising landfill costs."], ans: 0 },
      { q: "How much will the program cost in its first year?", opts: ["Eight hundred thousand dollars.", "One million dollars.", "One point two million dollars.", "One point five million dollars."], ans: 2 },
      { q: "What do critics of the program believe?", opts: ["Composting is not effective at reducing waste.", "The money should be used to upgrade recycling infrastructure.", "The collection schedule is not frequent enough.", "Residents should pay for their own composting bins."], ans: 1 }
    ]
  },
  { // Set B
    title: "Listening to a News Item",
    time: 300,
    desc: "You will hear a news report. Listen carefully and answer the questions that follow.",
    script: "This is CTV Barrie News. The town of Clearwater is celebrating the completion of the Lakeshore Heritage Trail, a twelve-kilometer multi-use pathway that connects the downtown waterfront district to the Pinewood Nature Reserve on the town's eastern boundary. The trail, which took three years and fourteen million dollars to complete, officially opens to the public this Saturday.\n\nMayor Richard Tran called the trail 'a transformative project for Clearwater' at a ribbon-cutting ceremony held earlier today. The pathway features separated lanes for cyclists and pedestrians, six rest stations with benches and water fountains, and three lookout points offering panoramic views of Lake Simcoe. Accessibility was a key priority in the design — all surfaces are wheelchair-friendly, and audio-guided information posts are available at historical landmarks along the route.\n\nThe trail is expected to boost local tourism significantly. According to the town's economic development office, a comparable trail in Collingwood generated approximately four million dollars in tourism revenue within its first two years. Local business owners near the trail have already reported increased interest, with two new cafés and a bike rental shop opening in anticipation of the trail's launch.\n\nEnvironmental groups have praised the project for preserving existing green spaces rather than paving over them. Ninety-two percent of the trail follows the natural shoreline and existing parkland, minimizing ecological disruption.",
    questions: [
      { q: "How long is the Lakeshore Heritage Trail?", opts: ["Eight kilometers.", "Ten kilometers.", "Twelve kilometers.", "Fifteen kilometers."], ans: 2 },
      { q: "How much did the trail cost to complete?", opts: ["Eight million dollars.", "Ten million dollars.", "Twelve million dollars.", "Fourteen million dollars."], ans: 3 },
      { q: "What accessibility feature does the trail include?", opts: ["Electric shuttle buses along the route.", "Audio-guided information posts at landmarks.", "Free wheelchair rentals at the entrance.", "Guide dogs available at rest stations."], ans: 1 },
      { q: "What economic impact is expected from the trail?", opts: ["It will create two hundred new jobs immediately.", "Property values will decrease near the trail.", "Tourism revenue comparable to Collingwood's trail success.", "The town will charge admission to cover costs."], ans: 2 },
      { q: "Why have environmental groups praised the project?", opts: ["It plants ten thousand new trees along the route.", "It runs entirely on solar-powered infrastructure.", "It preserves existing green spaces and follows the natural shoreline.", "It bans motorized vehicles in the entire downtown area."], ans: 2 }
    ]
  },
  { // Set C
    title: "Listening to a News Item",
    time: 300,
    desc: "You will hear a news report. Listen carefully and answer the questions that follow.",
    script: "Good morning from CBC Radio One. The city of Brampton is launching an innovative pilot program aimed at reducing traffic congestion and carbon emissions in one of Ontario's fastest-growing municipalities. Starting May first, the city will offer free public transit for all residents during off-peak hours — that's between ten AM and three PM on weekdays, and all day on weekends.\n\nThe program, called 'FreeRide Brampton,' will run for a six-month trial period. City officials estimate it will cost approximately three point five million dollars, funded through a combination of provincial transit grants and municipal reserves. During a press briefing yesterday, transit director Angela Chu stated that the goal is to increase bus ridership by at least twenty-five percent during off-peak periods, which currently run at only forty percent capacity.\n\n'We have buses running routes with very few passengers during the middle of the day,' Director Chu explained. 'By removing the fare barrier, we hope to attract residents who might otherwise drive alone, which reduces congestion and emissions simultaneously.'\n\nResidents have shown strong interest. An online registration portal launched last week has already received over nine thousand sign-ups. However, the local taxi and ride-share industry has voiced concerns, arguing that free transit could undercut their businesses. The city has committed to monitoring the impact on private transportation providers and will publish a full report at the end of the trial.",
    questions: [
      { q: "What is the FreeRide Brampton program?", opts: ["Free bicycle rentals at transit stations.", "Free public transit during off-peak hours.", "Discounted ride-sharing during rush hours.", "Free parking at city-owned lots."], ans: 1 },
      { q: "How long will the pilot program run?", opts: ["Three months.", "Six months.", "Nine months.", "One year."], ans: 1 },
      { q: "What is the ridership goal?", opts: ["To increase peak-hour ridership by fifty percent.", "To increase off-peak ridership by twenty-five percent.", "To double weekend ridership.", "To fill all buses to maximum capacity."], ans: 1 },
      { q: "How many people have already signed up?", opts: ["About three thousand.", "About five thousand.", "About nine thousand.", "About twelve thousand."], ans: 2 },
      { q: "Who has expressed concerns about the program?", opts: ["Environmental advocacy groups.", "The provincial government.", "The taxi and ride-share industry.", "Neighbouring municipalities."], ans: 2 }
    ]
  },
  { // Set D
    title: "Listening to a News Item",
    time: 300,
    desc: "You will hear a news report. Listen carefully and answer the questions that follow.",
    script: "Good evening. Health officials across Ontario are issuing a warning following a significant rise in influenza cases among children under twelve. According to the latest FluWatch report from the Public Health Agency of Canada, the number of children hospitalized with flu complications this season has already exceeded last year's total — and we are only halfway through the flu season.\n\nDr. Isaac Bogoch, an infectious disease specialist at Toronto General Hospital, says this year's dominant strain, Influenza A, is particularly aggressive in younger patients. He warns that the flu can lead to serious secondary infections, including pneumonia and ear infections, which may require hospitalization.\n\nHealth officials are urging parents to ensure all children over six months of age receive the flu vaccine immediately if they have not already. Children under five, the elderly, pregnant women, and those with underlying conditions such as asthma or diabetes are considered at the highest risk.\n\nSymptoms parents should watch for include a sudden fever above thirty-eight-point-five degrees Celsius, severe fatigue, body aches, and a persistent cough. Unlike a common cold, flu symptoms appear very quickly and more severely.\n\nDr. Bogoch also emphasized that keeping sick children home from school is critical to prevent community spread. Children should remain home for at least twenty-four hours after their fever breaks without fever-reducing medication.\n\nFree flu vaccines are available at most pharmacies and public health clinics. Appointments can be booked online or by calling your local health unit.",
    questions: [
      { q: "What is the main focus of the news report?", opts: ["The approval of a new flu vaccine in Ontario.", "A surge in flu hospitalizations among children.", "A warning about a new respiratory virus in schools.", "The closure of elementary schools due to illness."], ans: 1 },
      { q: "According to Dr. Bogoch, what can Influenza A lead to in younger patients?", opts: ["Long-term hearing loss.", "Secondary infections like pneumonia and ear infections.", "Severe allergic reactions.", "Permanent lung damage."], ans: 1 },
      { q: "Who is considered at the highest risk, according to officials?", opts: ["Teenagers and adults over sixty-five.", "Children over twelve and elderly men.", "Children under five, elderly, pregnant women, and those with health conditions.", "Teachers and daycare workers."], ans: 2 },
      { q: "How long should sick children stay home after their fever breaks?", opts: ["Until they feel completely better.", "For at least twenty-four hours after the fever breaks without medication.", "For a minimum of three school days.", "Until a doctor confirms they are no longer contagious."], ans: 1 },
      { q: "Where can residents get free flu vaccines?", opts: ["Only at hospital emergency departments.", "At most pharmacies and public health clinics.", "Exclusively at walk-in clinics with a referral.", "At designated community centres downtown."], ans: 1 }
    ]
  },
  { // Set E
    title: "Listening to a News Item",
    time: 300,
    desc: "You will hear a news report. Listen carefully and answer the questions that follow.",
    script: "Good morning. Residents in the Westdale and Riverside neighbourhoods of Burlington are facing a water service disruption following a major water main break that occurred overnight. The break, located on Glenwood Avenue near Parkside Drive, has left approximately forty-two hundred households without running water as crews work to contain the damage.\n\nThe water main, installed in nineteen eighty-three, ruptured at approximately two fifteen AM. Burlington Public Works Director Rachel Huang says the department became aware when pressure monitoring systems detected a sudden drop in water pressure across the affected zone. Crews were on site within the hour.\n\nResidents in the affected area are asked not to use their taps for drinking, cooking, or bathing until further notice. The city is distributing bottled water at three temporary stations: Westdale Community Centre on Mill Road, Riverside Arena on Lakeview Boulevard, and the Elmwood Public Library on King Street. Each household may collect up to two cases per visit.\n\nDirector Huang says crews are working around the clock and expect to restore service to most of the area by tomorrow evening, though some homes may experience low pressure or discoloured water for up to forty-eight hours after service resumes. Residents are advised to run their cold taps for several minutes before using water for drinking or cooking once service is restored.\n\nUpdates will be posted every four hours on the city's website at burlington.ca.",
    questions: [
      { q: "What caused the water service disruption?", opts: ["Heavy rainfall flooded the water treatment facility.", "A major water main break on Glenwood Avenue.", "Scheduled maintenance on the city's water system.", "A power outage at the central pumping station."], ans: 1 },
      { q: "How did the city first learn about the break?", opts: ["A resident called the emergency line.", "Pressure monitoring systems detected a drop in water pressure.", "Construction workers noticed water flooding the street.", "A local news crew reported the issue."], ans: 1 },
      { q: "How much bottled water may each household collect per visit?", opts: ["One case.", "Up to two cases.", "Three cases.", "Unlimited with proof of address."], ans: 1 },
      { q: "When does the city expect to restore service to most of the area?", opts: ["Later today.", "By tomorrow evening.", "Within forty-eight hours.", "By the end of the week."], ans: 1 },
      { q: "What are residents advised to do once water service is restored?", opts: ["Boil all water for ten minutes before drinking.", "Run their cold taps for several minutes before using water for consumption.", "Wait for a city official to inspect their plumbing.", "Call the public works office to confirm service is restored."], ans: 1 }
    ]
  },
  { // Set F
    title: "Listening to a News Item",
    time: 300,
    desc: "You will hear a news report. Listen carefully and answer the questions that follow.",
    script: "This is CBC Radio One. The City of Hamilton has announced the opening date for its long-awaited Rapid Transit B-Line — a new bus rapid transit corridor connecting the downtown core to Eastgate Square in the city's east end. The line officially begins service on Monday, March third, and is expected to carry up to twenty thousand passengers daily by the end of its first year.\n\nThe B-Line runs along the Main Street corridor for fourteen kilometres, with seventeen dedicated stops. Buses travel in dedicated lanes separated from regular traffic, meaning they will no longer be delayed by congestion. Service will run every five minutes during morning and evening peak hours, and every ten minutes during off-peak periods.\n\nHamilton Transit Director Priya Nair says the B-Line is part of the city's commitment to reducing car dependency. She noted that attracting even ten percent of current car commuters on this corridor to switch to transit could reduce Hamilton's annual greenhouse gas emissions by approximately thirty thousand tonnes.\n\nThe project cost a total of five hundred and forty million dollars, co-funded by the federal and provincial governments under the Public Transit Infrastructure Fund, with the City of Hamilton contributing twenty percent.\n\nOpponents, including a coalition of businesses along the corridor, have argued that the removal of on-street parking to create dedicated bus lanes has reduced customer accessibility and hurt retail traffic. City officials say they will conduct a six-month review of the economic impact on local businesses.",
    questions: [
      { q: "What is the main focus of the news report?", opts: ["The cancellation of a planned highway expansion.", "The opening of a new rapid transit line in Hamilton.", "A new fare increase on Hamilton Transit routes.", "The construction of a new subway station."], ans: 1 },
      { q: "How frequently will the B-Line run during peak hours?", opts: ["Every two minutes.", "Every five minutes.", "Every ten minutes.", "Every fifteen minutes."], ans: 1 },
      { q: "According to Director Nair, what environmental benefit is expected?", opts: ["Eliminating all diesel buses in Hamilton within two years.", "Reducing greenhouse gas emissions by attracting car commuters to transit.", "Planting trees along the entire corridor.", "Reducing noise pollution in residential areas."], ans: 1 },
      { q: "How much of the project's cost did the City of Hamilton contribute?", opts: ["Ten percent.", "Twenty percent.", "Forty percent.", "Fifty percent."], ans: 1 },
      { q: "What is the main concern raised by businesses along the corridor?", opts: ["The new buses are too loud.", "Bus service does not run late enough on weekends.", "The removal of parking to create bus lanes has reduced customer access.", "The fares are too expensive for low-income residents."], ans: 2 }
    ]
  }
];

const PART5_SETS = [
  { // Set A
    title: "Listening to a Discussion",
    time: 360,
    desc: "You will hear a discussion between three people. Listen carefully and answer the questions.",
    videoScene: "<h4>🎬 Video Scene Description</h4><p>Three colleagues — Aisha, Ben, and Carmen — are seated around a modern oval conference table in a brightly lit office meeting room. A large screen behind them shows a project timeline with the title 'Q3 Product Launch Plan.' Each person has a laptop open and a coffee mug on the table. Aisha is at the head of the table with printed notes in front of her.</p>",
    script: "Aisha: Okay, let's get started. We need to finalize our strategy for the Q3 product launch. We're about ten weeks out, and there are still some major decisions to make. Ben, can you give us an update on the marketing side?\n\nBen: Sure. So we've, um, confirmed the social media campaign — we're running targeted ads on Instagram, Facebook, and LinkedIn starting six weeks before launch. The budget for digital ads is forty thousand dollars, and we've reserved another fifteen thousand for influencer partnerships. My concern right now is the landing page. Our web team is behind schedule, and I'm worried it won't be ready in time for the pre-launch teaser.\n\nAisha: How far behind are they?\n\nBen: About two weeks. They say the delay is because of the new design system migration. I've escalated it, but I might need your help pushing it with the VP of engineering.\n\nCarmen: Can I jump in? On the sales side, I've been getting a lot of questions from our retail partners about pricing and availability. We originally said mid-July for the retail launch, but if the landing page is delayed, should we also push back the retail date?\n\nAisha: That's a good point. I don't think we should push back the retail date, though. The landing page primarily supports direct-to-consumer sales. Retail can proceed on its own timeline. Ben, do you agree?\n\nBen: Yeah, I think that's right. The retail partners have their own promotional materials. The landing page delay only affects our online channel.\n\nCarmen: Okay, that makes sense. One more thing — I've negotiated an exclusive two-week window with our largest retailer, ValueMart, where they'll be the only brick-and-mortar store carrying the product. In exchange, they've committed to featuring it in their weekly flyer and giving us end-cap displays in two hundred locations.\n\nAisha: That's fantastic, Carmen. Two hundred locations is huge visibility. Let's make sure we have enough inventory to support that. Ben, the influencer content should ideally go live the same week as the ValueMart launch to create maximum buzz.\n\nBen: Agreed. I'll coordinate the timing with the influencer agency.",
    questions: [
      { q: "How far away is the product launch?", opts: ["About six weeks.", "About eight weeks.", "About ten weeks.", "About twelve weeks."], ans: 2 },
      { q: "What is Ben's main concern?", opts: ["The social media ads are too expensive.", "The landing page may not be ready in time.", "The influencers are not well-known enough.", "The marketing budget has been cut."], ans: 1 },
      { q: "Why is the web team behind schedule?", opts: ["They lost two developers last month.", "They are working on a design system migration.", "The project requirements changed unexpectedly.", "They are waiting for content from marketing."], ans: 1 },
      { q: "What does Aisha decide about the retail launch date?", opts: ["It should be pushed back by two weeks.", "It should proceed as planned.", "It should be moved earlier to compensate.", "It should be cancelled entirely."], ans: 1 },
      { q: "What did Carmen negotiate with ValueMart?", opts: ["A permanent shelf space contract.", "A twenty percent discount on wholesale pricing.", "An exclusive two-week window with prominent displays.", "Free advertising in their national campaigns."], ans: 2 },
      { q: "How many store locations will feature the product?", opts: ["Fifty.", "One hundred.", "One hundred and fifty.", "Two hundred."], ans: 3 },
      { q: "What does Aisha suggest about the influencer content timing?", opts: ["It should launch a month before the product.", "It should go live the same week as the ValueMart launch.", "It should only run on weekends.", "It should be postponed until after launch reviews come in."], ans: 1 },
      { q: "What is Ben's role in the project?", opts: ["He manages the sales team.", "He handles the marketing and digital campaigns.", "He oversees product development.", "He coordinates logistics and shipping."], ans: 1 }
    ]
  },
  { // Set B
    title: "Listening to a Discussion",
    time: 360,
    desc: "You will hear a discussion between three people. Listen carefully and answer the questions.",
    videoScene: "<h4>🎬 Video Scene Description</h4><p>Three university students — David, Fatima, and Grace — are sitting at a round table in a campus library study room. Books and tablets are spread across the table. A whiteboard behind them shows 'Group Project: Urban Sustainability Report — Due April 18.' David has a pen in hand, doodling on his notepad. Fatima is looking at her laptop screen. Grace is flipping through a printed article.</p>",
    script: "David: Alright, so we need to figure out how we're splitting up the sustainability report. It's due in three weeks and we haven't even started the research phase.\n\nFatima: I've actually, um, already done some preliminary research on green building certifications — like LEED and BREEAM. I found some great case studies from Vancouver and Toronto that we could use.\n\nGrace: That's awesome, Fatima. I was thinking I could focus on urban transportation — specifically, how cities are transitioning to electric bus fleets and expanding bike-sharing programs. There's a lot of recent data from Montreal we could reference.\n\nDavid: Okay, that leaves me with... what? Waste management and water conservation?\n\nFatima: That could work perfectly. You could look at Calgary's zero-waste strategy and the rainwater harvesting systems they're testing in some Vancouver neighbourhoods.\n\nDavid: Fine, I'll take those two. Now, how are we structuring the report? The prof said it needs to be at least twenty-five pages with a minimum of fifteen academic sources.\n\nGrace: I think we should have an introduction, three main sections — one for each of our topics — a comparative analysis section, and a conclusion with recommendations. Each main section should be about six to seven pages.\n\nFatima: That sounds solid. For the comparative analysis, we could create a table comparing the three cities across all our topics. Visual representations always get bonus marks.\n\nDavid: Good idea. What about the presentation? She said it's worth thirty percent of the grade.\n\nGrace: I think we should use Canva or Google Slides and keep it visual — lots of infographics and minimal text on slides. We each present our own section, and then one of us does the conclusion. I'd volunteer for the conclusion since I'm, uh, comfortable with public speaking.\n\nDavid: Works for me. Let's set a deadline for the first drafts — how about ten days from now, so we have time to review and edit each other's work?\n\nFatima: Ten days is tight, but doable. Let's also meet again next Wednesday to check in on progress.",
    questions: [
      { q: "How many weeks do they have until the report is due?", opts: ["Two weeks.", "Three weeks.", "Four weeks.", "Five weeks."], ans: 1 },
      { q: "What topic is Fatima covering?", opts: ["Urban transportation systems.", "Green building certifications.", "Waste management and water conservation.", "Renewable energy strategies."], ans: 1 },
      { q: "Which city does Grace mention for transportation data?", opts: ["Vancouver.", "Toronto.", "Calgary.", "Montreal."], ans: 3 },
      { q: "How long must the report be?", opts: ["At least fifteen pages.", "At least twenty pages.", "At least twenty-five pages.", "At least thirty pages."], ans: 2 },
      { q: "What does Fatima suggest for the comparative analysis?", opts: ["A written summary paragraph.", "A comparison table across three cities.", "An interview with a sustainability expert.", "A video documentary presentation."], ans: 1 },
      { q: "What percentage of the grade is the presentation worth?", opts: ["Twenty percent.", "Twenty-five percent.", "Thirty percent.", "Thirty-five percent."], ans: 2 },
      { q: "Who volunteers to present the conclusion?", opts: ["David.", "Fatima.", "Grace.", "They haven't decided yet."], ans: 2 },
      { q: "When is the deadline for first drafts?", opts: ["Five days from now.", "One week from now.", "Ten days from now.", "Two weeks from now."], ans: 2 }
    ]
  },
  { // Set C
    title: "Listening to a Discussion",
    time: 360,
    desc: "You will hear a discussion between three people. Listen carefully and answer the questions.",
    videoScene: "<h4>🎬 Video Scene Description</h4><p>Three coworkers — Raj, Sophia, and Tyler — are standing around a high-top table in a modern open-plan office. Behind them, a large window shows a city skyline at midday. Each has a tablet or phone in hand. A poster on the wall reads 'Customer Satisfaction Week.' Raj is gesturing expressively while speaking.</p>",
    script: "Raj: So, the customer satisfaction survey results are in, and honestly, they're a mixed bag. Overall satisfaction dropped from eighty-two percent last quarter to seventy-six percent this quarter. We need to figure out why and what we're going to do about it.\n\nSophia: I looked at the breakdown. The biggest drops were in two areas: response time and issue resolution. Customers said they're waiting an average of four minutes on hold before speaking to an agent, up from two minutes last quarter. And about thirty percent said their issue wasn't fully resolved on the first call.\n\nTyler: Those numbers are concerning. On the response time side, I think the issue is staffing. We lost three agents last month and haven't replaced them yet. The remaining team is stretched thin, especially during the eleven AM to two PM rush.\n\nRaj: I agree we need to hire, but that takes time. What can we do, um, in the short term to bring that hold time down?\n\nSophia: We could implement a callback system. Instead of waiting on hold, customers leave their number, and an agent calls them back within a specified window — say, thirty minutes. It's a better experience, and it reduces the pressure on the live queue.\n\nTyler: I like that idea. For the resolution issue, I think we need better training materials. A lot of the newer agents don't know how to handle complex cases, so they either escalate unnecessarily or give incomplete answers.\n\nRaj: Fair point. Let's create a knowledge base — a searchable database with step-by-step solutions for the fifty most common issues. That way, agents can quickly find accurate answers during a call.\n\nSophia: That's a great idea, Raj. I can start compiling the top issues from our ticket system. Tyler, could you work with the training team on updating the onboarding curriculum?\n\nTyler: Absolutely. I'll set up a meeting with them this week.\n\nRaj: Perfect. Let's aim to have both the callback system and the knowledge base in place within four weeks. I want to see those numbers back above eighty percent by next quarter.",
    questions: [
      { q: "What is the current overall satisfaction rate?", opts: ["Seventy percent.", "Seventy-six percent.", "Eighty-two percent.", "Eighty-five percent."], ans: 1 },
      { q: "What are the two main areas where scores dropped?", opts: ["Product quality and pricing.", "Response time and issue resolution.", "Website usability and delivery speed.", "Agent friendliness and technical knowledge."], ans: 1 },
      { q: "What is the average hold time now?", opts: ["Two minutes.", "Three minutes.", "Four minutes.", "Five minutes."], ans: 2 },
      { q: "Why does Tyler think response time has increased?", opts: ["The phone system was recently upgraded.", "Call volumes have unexpectedly doubled.", "Three agents left and haven't been replaced.", "Agents are spending too long on each call."], ans: 2 },
      { q: "What short-term solution does Sophia suggest?", opts: ["Hire temporary staff from an agency.", "Implement a customer callback system.", "Reduce operating hours to focus on quality.", "Add a self-service chatbot on the website."], ans: 1 },
      { q: "What does Raj propose for the resolution problem?", opts: ["Fire underperforming agents.", "Create a searchable knowledge base.", "Outsource complex cases to a specialist team.", "Require customers to submit issues by email only."], ans: 1 },
      { q: "What task does Tyler agree to take on?", opts: ["Compiling the top issues from the ticket system.", "Meeting with the training team about onboarding.", "Building the callback system software.", "Presenting the results to upper management."], ans: 1 },
      { q: "What is Raj's target satisfaction rate for next quarter?", opts: ["Above seventy-five percent.", "Above seventy-eight percent.", "Above eighty percent.", "Above eighty-five percent."], ans: 2 }
    ]
  },
  { // Set D
    title: "Listening to a Discussion",
    time: 360,
    desc: "You will hear a discussion between three people. Listen carefully and answer the questions.",
    videoScene: "<h4>🎬 Video Scene Description</h4><p>Three people — Linda (moderator), Kevin, and Sophie — are seated around a small round table in a community centre meeting room. A whiteboard behind them reads 'Community Garden Hours Review.' Linda has an agenda sheet in front of her. Kevin is leaning forward with his arms on the table. Sophie sits upright with her arms crossed.</p>",
    script: "Linda: Thanks everyone for coming. We're here to discuss whether the Ridgewood Community Garden should extend its access hours from the current six AM to eight PM schedule to the proposed five AM to ten PM. Sophie and Kevin, you've both been vocal on opposite sides. Kevin, let's start with you.\n\nKevin: Thanks, Linda. I'm a landscaper and often work long days in summer. The only time I can realistically get to my plot is early morning or after work. Right now I arrive at eight fifteen and find the gates already locked. Extending to five AM and ten PM would make a real difference for working people like me.\n\nSophie: I understand Kevin's frustration, but I live directly behind the garden fence and have two young kids in bed by eight. The current hours already occasionally cause issues — people talking, running water, tools clanging. Pushing to ten PM means two more hours of noise every evening. That's not reasonable.\n\nKevin: Most gardeners are quiet people. We could put in a noise guideline — anything electrical stops at eight, but people could water and tend plants quietly until ten.\n\nSophie: That's a reasonable compromise, I'll admit. But who enforces it? There's no on-site staff after seven PM now.\n\nLinda: The Parks Department mentioned they could introduce a volunteer community steward role — a rotating two-hour supervision shift taken on by garden members each month. Would that address your concern, Sophie?\n\nSophie: If it's well-organized and consistent, yes, I could support a limited extension — maybe nine PM, not ten. That feels more balanced.\n\nKevin: Nine PM works for me. That gives me enough time after work.\n\nLinda: Great. It sounds like we have a potential consensus around extending to nine PM with a noise guideline and a volunteer steward system. I'll bring this to the Parks Department for formal approval.",
    questions: [
      { q: "What is the main topic of the discussion?", opts: ["Whether to add more plots to the community garden.", "Whether to extend the garden's opening hours.", "Whether to introduce paid membership for the garden.", "Whether to hire a full-time garden manager."], ans: 1 },
      { q: "Why does Kevin want the hours extended?", opts: ["He prefers to garden at night.", "As a working person, he often misses the current opening window.", "He runs a business from the garden.", "He thinks the garden is too crowded during current hours."], ans: 1 },
      { q: "What is Sophie's main concern?", opts: ["Extended hours would attract vandals.", "Noise from the garden would disturb her family including her children.", "The garden equipment could be stolen at night.", "She is worried about the cost of extended utilities."], ans: 1 },
      { q: "What compromise does Kevin propose about noise?", opts: ["Ban all gardening after eight PM.", "Restrict electrical tools after eight but allow quiet activities until ten.", "Require gardeners to wear noise-cancelling headphones.", "Install soundproof fencing around the garden."], ans: 1 },
      { q: "What volunteer system does Linda propose?", opts: ["A paid part-time Parks Department staff member.", "A rotating garden steward shift taken on by garden members.", "A new subcommittee to manage noise complaints.", "A partnership with local police for evening patrols."], ans: 1 },
      { q: "What extended closing time does Sophie ultimately agree to support?", opts: ["Eight PM.", "Eight thirty PM.", "Nine PM.", "Ten PM."], ans: 2 },
      { q: "What is Linda's next step after the discussion?", opts: ["Hold a community vote.", "Take the proposal to the Parks Department for formal approval.", "Write a report to City Council.", "Hire a volunteer coordinator immediately."], ans: 1 },
      { q: "What reason does Kevin give for accepting nine PM?", opts: ["It is within the city's noise bylaw requirements.", "It gives him enough time to garden after work.", "He lives close to the garden and doesn't need early access.", "He agreed to compromise to maintain goodwill with Sophie."], ans: 1 }
    ]
  },
  { // Set E
    title: "Listening to a Discussion",
    time: 360,
    desc: "You will hear a discussion between three people. Listen carefully and answer the questions.",
    videoScene: "<h4>🎬 Video Scene Description</h4><p>Three people — Sarah (manager), Nadia, and Marcus — are seated in a bright modern boardroom. Sarah is at the head of the table with a laptop open. Nadia has printed notes. Marcus has a coffee mug and appears relaxed. A whiteboard reads 'Hybrid Work Policy — New Fiscal Year.'</p>",
    script: "Sarah: Thanks for joining. We need to finalize our hybrid work policy for the new fiscal year. Currently there's no formal policy — some people are in every day, others barely come in. I want to establish clear expectations. Nadia, Marcus, what are your thoughts?\n\nNadia: I think we should anchor everyone to at least three days in the office. Teams function better with that kind of face time. Since people started working remotely more, there's been a real drop in informal communication — the quick conversations that spark ideas. Junior staff especially need to be around experienced colleagues to learn.\n\nMarcus: I hear you, Nadia, but three mandatory days feels like a lot to me. My team's output has been consistently high. I'd argue that two days in the office is plenty for collaboration, and it gives people more flexibility.\n\nSarah: Let's think about which days matter most. Tuesday, Wednesday, and Thursday tend to be our peak collaboration days. Mondays and Fridays are lighter — a lot of people use Fridays for individual admin work anyway.\n\nNadia: Exactly. If we anchor Tuesday through Thursday in-office, the whole team is present in a consistent window without losing the quieter bookend days.\n\nMarcus: I could live with that. So Tuesday and Wednesday mandatory for everyone?\n\nSarah: Let's say Tuesday and Wednesday are mandatory for all staff. Thursday is mandatory for people managers only, since that's when we do one-on-ones and team reviews. Individual contributors can choose whether to come in Thursday.\n\nNadia: Fair. I'd add one caveat — new employees in their first six months should be in-office four days per week during onboarding.\n\nMarcus: Agreed. And we should review the policy in six months to see how it's working.\n\nSarah: Perfect. I'll draft this for HR approval by end of week.",
    questions: [
      { q: "What is the purpose of this meeting?", opts: ["To decide whether to close the company's main office.", "To finalize a formal hybrid work policy.", "To discuss performance reviews for remote employees.", "To set up a new remote work technology system."], ans: 1 },
      { q: "What problem does Nadia identify with the current arrangement?", opts: ["Productivity data has dropped company-wide.", "There has been a decline in informal communication since remote work began.", "Employees are working too many hours from home.", "The office is too large for the number of people coming in."], ans: 1 },
      { q: "How many mandatory in-office days does Marcus suggest?", opts: ["One day.", "Two days.", "Three days.", "Four days."], ans: 1 },
      { q: "Why does Sarah identify Tuesday through Thursday as important?", opts: ["The office building is only open those three days.", "They are the peak collaboration days for the team.", "These days have the best public transit connections.", "They are the least busy days with the fewest meetings."], ans: 1 },
      { q: "Under the final agreement, which days are mandatory for all staff?", opts: ["Monday and Tuesday.", "Tuesday and Wednesday.", "Wednesday and Thursday.", "Tuesday, Wednesday, and Thursday."], ans: 1 },
      { q: "Who is required to come in on Thursdays?", opts: ["All employees equally.", "Junior staff only.", "People managers only.", "Only senior individual contributors."], ans: 2 },
      { q: "What exception does Nadia propose for new employees?", opts: ["They must work full-time in the office permanently.", "They should work from home exclusively during onboarding.", "They should be in the office four days a week for their first six months.", "They are allowed to choose any schedule they prefer."], ans: 2 },
      { q: "What does Marcus suggest at the end of the meeting?", opts: ["That the policy should be decided by employee vote.", "That the policy should be reviewed in six months.", "That all meetings should move to video calls.", "That the policy should be indefinitely delayed."], ans: 1 }
    ]
  },
  { // Set F
    title: "Listening to a Discussion",
    time: 360,
    desc: "You will hear a discussion between three people. Listen carefully and answer the questions.",
    videoScene: "<h4>🎬 Video Scene Description</h4><p>Three educators — Mr. Park, Mrs. Allen, and Ms. Ortega — are seated around a rectangular table in a school staffroom. A whiteboard behind them shows 'ROM Trip — March 14.' Mr. Park has a clipboard. Mrs. Allen is typing on a laptop. Ms. Ortega holds a printed flyer from the Royal Ontario Museum.</p>",
    script: "Mr. Park: OK, we've confirmed the Royal Ontario Museum trip for March fourteenth. We have ninety-three grade seven students going, and we need to finalize logistics today. Mrs. Allen, can you start with transportation?\n\nMrs. Allen: I've contacted the transportation company. They can provide two fifty-passenger coaches. That gives us enough room for all students plus chaperones. The cost is four hundred and fifty dollars per bus — nine hundred dollars total.\n\nMr. Park: Can we ask parents to cover the full amount, or does the school cover part?\n\nMrs. Allen: The school's activity fund covers up to three hundred dollars. That leaves six hundred divided among the students — roughly six-fifty each.\n\nMs. Ortega: I'd round that up to seven dollars per student to give us a small buffer. Also, the museum offers two options for school groups. Option A is general admission at nine-fifty per student. Option B is twelve dollars and includes a guided tour of the Ancient Egypt and Indigenous Canada exhibits.\n\nMr. Park: Option B sounds more educational — we're covering both ancient civilizations and Canadian Indigenous history this term. I'd go with the guided tour.\n\nMrs. Allen: So total per student is seven dollars transportation plus twelve dollars admission — nineteen dollars.\n\nMs. Ortega: We also need one adult chaperone per ten students. So at least ten chaperones. I have three parent volunteers confirmed. Do either of you have more?\n\nMr. Park: I have four confirmed, and Mrs. Chen said she'd join as well.\n\nMrs. Allen: I can bring two more. That's ten total — perfect.\n\nMr. Park: Great. I'll send permission forms and payment packages home this Friday.",
    questions: [
      { q: "How many students are going on the trip?", opts: ["Seventy-five.", "Eighty-eight.", "Ninety-three.", "One hundred."], ans: 2 },
      { q: "What is the total transportation cost?", opts: ["Four hundred and fifty dollars.", "Seven hundred dollars.", "Nine hundred dollars.", "One thousand two hundred dollars."], ans: 2 },
      { q: "How much does the school activity fund contribute?", opts: ["One hundred and fifty dollars.", "Two hundred dollars.", "Two hundred and fifty dollars.", "Three hundred dollars."], ans: 3 },
      { q: "Why does Mr. Park prefer Option B for the museum visit?", opts: ["It is less expensive than Option A.", "It includes lunch for students.", "It matches the topics they are currently studying.", "It is the only option available for large groups."], ans: 2 },
      { q: "What is the total cost per student for the trip?", opts: ["Twelve dollars.", "Sixteen dollars.", "Nineteen dollars.", "Twenty-two dollars."], ans: 2 },
      { q: "What is the required adult-to-student ratio?", opts: ["One adult per five students.", "One adult per eight students.", "One adult per ten students.", "One adult per fifteen students."], ans: 2 },
      { q: "How many total chaperones are confirmed by the end of the discussion?", opts: ["Eight.", "Nine.", "Ten.", "Twelve."], ans: 2 },
      { q: "What does Mr. Park plan to send home on Friday?", opts: ["A museum itinerary and tour topics.", "Permission forms and payment collection packages.", "A summary of the guided tour content.", "A request for additional volunteers."], ans: 1 }
    ]
  }
];

const PART6_SETS = [
  { // Set A
    title: "Listening for Viewpoints",
    time: 480,
    desc: "You will hear a speaker presenting different viewpoints on a topic. Listen carefully and answer the questions.",
    script: "Today, I'd like to explore a topic that's generating significant debate in cities across Canada: the question of whether municipalities should ban single-use plastics, or whether the focus should instead be on improving recycling infrastructure.\n\nProponents of an outright ban argue that single-use plastics — things like straws, bags, cutlery, and takeout containers — are fundamentally wasteful. They point out that despite decades of recycling campaigns, only about nine percent of plastic ever produced globally has actually been recycled. The rest ends up in landfills, oceans, or is incinerated. Supporters of a ban say that recycling, um, creates a false sense of environmental responsibility. People feel good about tossing a plastic container into the blue bin, but the reality is that much of it never gets processed. A ban, they argue, would force businesses and consumers to adopt genuinely sustainable alternatives — like compostable containers, reusable bags, and paper-based packaging.\n\nOn the other hand, opponents of a ban raise several practical concerns. First, they argue that alternatives to plastic aren't always more environmentally friendly. Paper bags, for example, require significantly more water and energy to produce than plastic bags. Compostable containers often only break down in industrial composting facilities, which many municipalities don't have. If these items end up in a regular landfill, they decompose no faster than conventional plastics.\n\nSecondly, small business owners worry about the financial impact. A restaurant that switches from plastic to compostable takeout containers might see its packaging costs increase by forty to sixty percent. For a small business already operating on thin margins, that's a significant burden.\n\nA third perspective — and one that's gaining traction — is a hybrid approach. Under this model, municipalities would ban the most problematic single-use items, like plastic straws and polystyrene foam, while simultaneously investing in better recycling and composting infrastructure. This approach acknowledges that plastic, when properly recycled, can have a lower environmental impact than some alternatives, while still addressing the most harmful products that rarely get recycled.\n\nUltimately, whatever path cities choose, experts agree that public education is the critical missing piece. Without widespread understanding of what can and cannot be recycled — and why it matters — any policy will fall short of its goals.",
    questions: [
      { q: "What percentage of plastic produced globally has been recycled?", opts: ["About five percent.", "About nine percent.", "About fifteen percent.", "About twenty percent."], ans: 1 },
      { q: "According to ban supporters, what does recycling create?", opts: ["A profitable industry for municipalities.", "A false sense of environmental responsibility.", "New jobs in the manufacturing sector.", "Higher taxes for property owners."], ans: 1 },
      { q: "What concern do opponents raise about paper bags?", opts: ["They are too small for most shopping needs.", "They cannot be recycled at all.", "They require more water and energy to produce.", "They contain harmful chemicals."], ans: 2 },
      { q: "By how much could packaging costs increase for small businesses?", opts: ["Ten to twenty percent.", "Twenty to thirty percent.", "Forty to sixty percent.", "Seventy to ninety percent."], ans: 2 },
      { q: "What does the hybrid approach propose?", opts: ["Ban all plastics and switch entirely to paper.", "Ban the most harmful items while improving recycling infrastructure.", "Let the free market decide without government intervention.", "Tax plastic products and use revenue for environmental cleanup."], ans: 1 },
      { q: "What do experts say is the critical missing piece?", opts: ["Stricter law enforcement.", "International trade agreements.", "Public education about recycling.", "Higher taxes on plastic manufacturers."], ans: 2 }
    ]
  },
  { // Set B
    title: "Listening for Viewpoints",
    time: 480,
    desc: "You will hear a speaker presenting different viewpoints on a topic. Listen carefully and answer the questions.",
    script: "Remote work has become one of the most hotly debated topics in the modern workplace since the pandemic fundamentally changed how we think about where we work. Today, I want to examine the different perspectives on whether companies should embrace permanent remote work or require employees to return to the office.\n\nAdvocates of remote work point to several compelling benefits. Studies have consistently shown that remote workers report higher job satisfaction — one major survey found that seventy-eight percent of remote employees said they were happier compared to their in-office days. Productivity research also supports this view: a Stanford study of over sixteen thousand workers found a thirteen percent increase in productivity among those who worked from home. Remote work also expands the talent pool for employers. A company in Halifax can now hire a software developer in, um, Kelowna or Winnipeg without requiring relocation.\n\nHowever, critics of full-time remote work raise important counterpoints. They argue that collaboration and innovation suffer when teams aren't physically together. Spontaneous hallway conversations, whiteboard brainstorming sessions, and informal mentoring relationships are difficult to replicate over video calls. Some research suggests that while individual productivity on defined tasks increases remotely, creative problem-solving and complex team projects actually decline by up to twenty percent.\n\nThere's also the issue of employee well-being. While some employees thrive remotely, others report feeling isolated, disconnected from company culture, and struggle with work-life boundaries. Junior employees, in particular, may miss out on the observational learning that happens naturally in an office environment — watching how senior colleagues handle client calls, navigate office politics, or present ideas in meetings.\n\nA growing number of companies are adopting a hybrid model as a middle ground. Under this arrangement, employees typically come into the office two or three days a week for meetings and collaborative work, and spend the remaining days working remotely. Proponents of the hybrid model say it combines the best of both worlds: the flexibility and focus time of remote work with the social connection and collaboration benefits of in-person interaction.\n\nCritics of the hybrid model, however, call it the worst of both worlds. They argue it creates scheduling headaches, underutilizes expensive office space, and results in a two-tier culture where in-office employees get more face time with leadership and, consequently, more career advancement opportunities.",
    questions: [
      { q: "What percentage of remote employees reported higher happiness?", opts: ["Sixty-five percent.", "Seventy percent.", "Seventy-eight percent.", "Eighty-five percent."], ans: 2 },
      { q: "What did the Stanford study find about remote work productivity?", opts: ["A five percent decrease.", "No significant change.", "A thirteen percent increase.", "A twenty percent increase."], ans: 2 },
      { q: "According to critics, what declines in remote work settings?", opts: ["Employee retention rates.", "Individual task completion speed.", "Creative problem-solving and complex team projects.", "Compliance with company policies."], ans: 2 },
      { q: "Who may be most disadvantaged by remote work?", opts: ["Senior executives.", "Part-time workers.", "Junior employees.", "Technical specialists."], ans: 2 },
      { q: "What is the typical hybrid model schedule?", opts: ["One day in office, four days remote.", "Two or three days in office per week.", "Alternating weeks in office and remote.", "Full-time office with one remote day."], ans: 1 },
      { q: "What do critics say about the hybrid model?", opts: ["It is too expensive to implement.", "It can create a two-tier culture and scheduling problems.", "It violates employment standards legislation.", "It is only suitable for large corporations."], ans: 1 }
    ]
  },
  { // Set C
    title: "Listening for Viewpoints",
    time: 480,
    desc: "You will hear a speaker presenting different viewpoints on a topic. Listen carefully and answer the questions.",
    script: "The debate over whether to introduce congestion pricing in major Canadian cities has intensified in recent years, and today I want to present the various perspectives on this increasingly relevant issue.\n\nCongestion pricing is a system where drivers are charged a fee to enter designated high-traffic zones during peak hours. Cities like London, Stockholm, and Singapore have implemented versions of this approach with, supporters say, remarkable success. London, for example, saw a thirty percent reduction in traffic within the congestion zone after introducing its charge in 2003, and Stockholm reported a twenty-two percent decrease.\n\nAdvocates argue that congestion pricing is the most effective tool for reducing urban gridlock. They point out that the average Canadian commuter spends thirty-two minutes each way commuting, and in cities like Toronto and Vancouver, this figure can exceed an hour. The economic cost of congestion across Canada is estimated at approximately three point three billion dollars annually in lost productivity. By making driving during peak hours more expensive, proponents say, you incentivize people to carpool, take public transit, shift their hours, or work from home.\n\nOpponents, however, raise serious equity concerns. They argue that congestion pricing is essentially a regressive tax — it affects lower-income workers disproportionately, especially those in service industries who must commute during peak hours and cannot work remotely. A janitor or a retail worker doesn't have the luxury of, um, adjusting their schedule or working from home. If the daily charge is fifteen dollars each way, that's over six thousand dollars a year — a significant financial burden for someone earning minimum wage.\n\nThere's also skepticism about whether the revenue generated would actually be reinvested in public transit, as proponents promise. Critics point to historical examples where dedicated transportation funds were redirected to general government spending.\n\nA nuanced position suggests that congestion pricing could work, but only if it's paired with substantial improvements to public transit first. You can't charge people to drive if you don't offer them a viable alternative. This means more frequent bus and rail service, expanded routes to underserved areas, and reduced fares — all of which require significant upfront investment before a congestion charge would be fair to implement.",
    questions: [
      { q: "What is congestion pricing?", opts: ["A tax on fuel purchases in urban areas.", "A fee charged to drivers entering high-traffic zones during peak hours.", "A system of tolls on all major highways.", "A fine for driving over the speed limit in cities."], ans: 1 },
      { q: "By how much did London reduce traffic with congestion pricing?", opts: ["Fifteen percent.", "Twenty-two percent.", "Thirty percent.", "Forty percent."], ans: 2 },
      { q: "What is the estimated annual cost of congestion in Canada?", opts: ["About one billion dollars.", "About two billion dollars.", "About three point three billion dollars.", "About five billion dollars."], ans: 2 },
      { q: "Why do opponents call congestion pricing a 'regressive tax'?", opts: ["It gives tax breaks to wealthy corporations.", "It disproportionately burdens lower-income workers.", "It reduces government revenue from fuel taxes.", "It penalizes people who live in rural areas."], ans: 1 },
      { q: "What is a major concern about the revenue raised?", opts: ["It may not cover the cost of the program.", "It could be redirected away from transit.", "It would go to private companies, not the government.", "It would cause ticket prices to increase."], ans: 1 },
      { q: "What condition does the nuanced position say must be met first?", opts: ["Congestion must reach a critical threshold.", "Voter approval through a public referendum.", "Substantial improvements to public transit.", "Agreement from all neighbouring municipalities."], ans: 2 }
    ]
  },
  { // Set D
    title: "Listening for Viewpoints",
    time: 480,
    desc: "You will hear a speaker presenting different viewpoints on a topic. Listen carefully and answer the questions.",
    script: "Today I'd like to examine the growing debate around the four-day workweek — specifically, whether a compressed schedule of thirty-two paid hours should become a new standard in Canada.\n\nSupporters point to several pilot studies conducted in Iceland, the UK, Japan, and New Zealand. The largest UK trial, run in 2022 and 2023, involved over sixty companies and nearly three thousand employees. At the end of the trial, ninety-two percent of companies said they intended to keep the policy permanently. Worker-reported stress and burnout dropped significantly, sick day usage declined by about thirty percent, and self-reported productivity remained equal to or better than before. Advocates argue that longer rest periods make workers more focused and creative during the hours they do work.\n\nCritically, this model doesn't ask employees to work forty hours across four days — that would just be four brutal ten-hour days. The thirty-two-hour model works because it prioritizes deep, focused work while eliminating unnecessary meetings and low-value tasks that inflate the traditional workweek without adding real output.\n\nOpponents raise important practical concerns. Healthcare, emergency services, retail, and hospitality industries cannot simply close on Fridays. In these sectors, a four-day workweek for individual employees means employers need to hire additional staff to maintain coverage — increasing labour costs by fifteen to twenty percent for some operations.\n\nCritics also point out that the UK pilot was largely self-selected, meaning companies that volunteered were already progressive, flexible workplaces likely to succeed. Generalizing the results to the entire economy may be premature.\n\nThere's also an equity issue. Knowledge workers in offices — the majority of four-day workweek advocates — stand to benefit most. Service workers, who are often paid by the hour and already work irregular schedules, would gain little from a policy designed around salaried, desk-based employment.\n\nThe question is not whether a four-day workweek can work — clearly it can, in the right environments. The question is whether it's fair, feasible, and economically sound to implement as a broad national standard.",
    questions: [
      { q: "What was the result of the UK pilot regarding company intentions?", opts: ["Thirty percent of companies planned to continue the policy.", "Sixty percent wanted to continue on a trial basis.", "Ninety-two percent intended to make the policy permanent.", "All companies returned to the five-day model."], ans: 2 },
      { q: "By how much did sick day usage decline in the pilot?", opts: ["About ten percent.", "About twenty percent.", "About thirty percent.", "About fifty percent."], ans: 2 },
      { q: "What is important about the thirty-two-hour model, according to the speaker?", opts: ["It compresses forty hours into four longer days.", "It eliminates low-value tasks to maintain productivity in fewer hours.", "It requires employees to work faster than before.", "It relies on automation to fill the gap."], ans: 1 },
      { q: "In which types of industries do critics say the four-day workweek creates staffing problems?", opts: ["Software and technology firms.", "Financial services and banking.", "Healthcare, retail, hospitality, and emergency services.", "Education and government."], ans: 2 },
      { q: "What criticism is raised about the UK pilot study?", opts: ["It ran for too long to be scientifically valid.", "It was conducted in only one city.", "The participating companies were self-selected and already had flexible cultures.", "The results were never published publicly."], ans: 2 },
      { q: "Who does the speaker say would benefit least from a four-day workweek policy?", opts: ["Salaried knowledge workers in offices.", "Government employees with fixed schedules.", "Senior executives and managers.", "Hourly service workers with irregular schedules."], ans: 3 }
    ]
  },
  { // Set E
    title: "Listening for Viewpoints",
    time: 480,
    desc: "You will hear a speaker presenting different viewpoints on a topic. Listen carefully and answer the questions.",
    script: "Good morning. Today I want to discuss a growing workplace issue that affects millions of Canadians: the right to disconnect from work communications outside of regular hours.\n\nOntario became the first Canadian province to legislate this right in 2022, requiring employers with twenty-five or more employees to have a written policy on employees' right to disconnect. Similar laws exist in France, Spain, Portugal, and parts of Latin America.\n\nAdvocates argue that technology has fundamentally blurred the boundary between work time and personal time. Before smartphones, when you left the office at five PM, you were genuinely off work. Today, employees face an almost constant stream of after-hours emails and notifications — what researchers call an 'always-on' work culture.\n\nStudies from the University of British Columbia and McMaster University suggest that the mere expectation of being reachable after hours — even when workers don't actually respond — raises cortisol levels, a biological indicator of stress. Over time, this contributes to burnout, anxiety, and reduced job satisfaction. Interestingly, this effect is strongest for conscientious employees — precisely the people organizations most want to keep.\n\nSupporters of stronger protections argue that the current Ontario legislation is insufficient. It requires companies to have a policy — but places no obligation on the content of that policy. A company could write a policy saying employees are expected to respond within one hour at all times, and that would still comply with the law.\n\nCritics of stronger legislation argue that in many professional environments, some after-hours communication is inevitable and even preferred by employees themselves. A software developer might prefer to send a message at nine PM and then sleep in, rather than holding the thought until morning. Rigid restrictions could reduce team flexibility and create bureaucratic burdens for small businesses.\n\nThe core challenge is finding a balance — acknowledging that technology has changed work, while avoiding policies so rigid they remove the flexibility modern workers actually value.",
    questions: [
      { q: "What was significant about Ontario's 2022 legislation?", opts: ["It banned all work communication after five PM.", "It made Ontario the first Canadian province to legislate the right to disconnect.", "It required employers to provide smartphones to all employees.", "It introduced mandatory overtime pay for after-hours communication."], ans: 1 },
      { q: "What do university studies suggest about the expectation of being reachable after hours?", opts: ["It causes permanent memory loss in employees.", "Even without responding, the expectation raises stress hormone levels.", "It improves employee productivity significantly.", "It has no measurable effect on employee health."], ans: 1 },
      { q: "Which group of employees is most affected by after-hours stress?", opts: ["Employees who frequently ignore work messages.", "Part-time and contract workers.", "Conscientious employees who care about their work.", "Employees in management positions only."], ans: 2 },
      { q: "What is a major criticism of Ontario's current legislation?", opts: ["It only applies to the public sector.", "It applies to all employers regardless of size.", "It requires a policy to exist but doesn't regulate what the policy must say.", "It has never been enforced against any employer."], ans: 2 },
      { q: "What argument do critics of stronger legislation make?", opts: ["After-hours communication should be encouraged for productivity.", "Some after-hours communication is preferred by workers and adds flexibility.", "Companies should have the right to monitor all communications.", "The legislation will cause companies to move operations overseas."], ans: 1 },
      { q: "What does the speaker identify as the core challenge?", opts: ["Convincing employees to stop checking phones after work.", "Getting all provinces to adopt similar legislation.", "Balancing acknowledgment of technology's impact with avoiding overly rigid policies.", "Funding additional government enforcement of workplace laws."], ans: 2 }
    ]
  },
  { // Set F
    title: "Listening for Viewpoints",
    time: 480,
    desc: "You will hear a speaker presenting different viewpoints on a topic. Listen carefully and answer the questions.",
    script: "Today I want to examine one of the most pressing policy questions of our time: should governments regulate the amount of time children spend on social media platforms?\n\nIn recent years, a growing body of research has linked heavy social media use among adolescents to rising rates of anxiety, depression, and poor body image — particularly among girls aged eleven to sixteen. A landmark study from the University of Oxford reviewed data from over thirty-five thousand teenagers and found that heavy social media use — defined as more than three hours per day on platforms like Instagram, TikTok, and Snapchat — was associated with measurably lower psychological well-being. The study found the relationship was stronger for girls than boys and most significant during early adolescence.\n\nAustralia passed legislation in 2024 banning children under sixteen from holding social media accounts — the strictest such law in the world. Supporters of this approach argue that children are neurologically and emotionally ill-equipped to handle social comparison, cyberbullying, and the dopamine-driven feedback loops built into platform design. They argue that just as society restricts children's access to alcohol and gambling, it has a responsibility to protect minors from psychologically harmful digital environments.\n\nOpponents argue that broad bans are blunt instruments that don't address the underlying problem — the design of the platforms themselves. Banning children from platforms doesn't make those platforms safer; it simply delays exposure. Critics also raise concerns about enforcement: age verification systems online are imperfect and easily circumvented, meaning bans may primarily affect compliant children while doing little for those in vulnerable situations.\n\nA third perspective focuses on digital literacy — teaching children how to use social media mindfully and critically rather than restricting access entirely. Proponents of this approach argue that social media is an inseparable part of modern social life, and that children need guidance on how to navigate it safely, not a prohibition they will soon outgrow.\n\nUltimately, the conversation reflects a deeper tension between protection and preparation — between shielding children from harm and equipping them to handle an increasingly digital world.",
    questions: [
      { q: "What did the University of Oxford study find about heavy social media use in teens?", opts: ["It improved academic performance in children over fourteen.", "It was associated with lower psychological well-being in teenagers.", "It had no significant effect on children's mental health.", "It primarily affected boys more than girls."], ans: 1 },
      { q: "How many hours per day was defined as 'heavy' social media use in the study?", opts: ["More than one hour.", "More than two hours.", "More than three hours.", "More than five hours."], ans: 2 },
      { q: "What action did Australia take in 2024?", opts: ["They required parental consent for accounts for children under eighteen.", "They limited social media use to one hour per day for minors.", "They banned children under sixteen from holding social media accounts.", "They introduced mandatory digital literacy courses in all schools."], ans: 2 },
      { q: "What comparison do supporters of a ban make to justify their position?", opts: ["They compare social media to tobacco companies targeting young users.", "They compare restricting social media to society's existing limits on alcohol and gambling for minors.", "They argue social media should be treated like a school subject.", "They reference restrictions placed on violent video games."], ans: 1 },
      { q: "What do critics say is the main flaw with outright bans?", opts: ["They would cause social media companies to close entirely.", "They are unconstitutional in most countries.", "Bans don't fix platform design and are easily circumvented.", "They only affect children from low-income households."], ans: 2 },
      { q: "What does the digital literacy approach propose?", opts: ["That children should be permanently kept off all social media.", "That schools should teach children to use social media mindfully rather than banning access.", "That parents should be fined for allowing underage access.", "That social media platforms should be replaced with educational tools."], ans: 1 }
    ]
  }
];
