// CELPIP Reading Test - Parts 3 & 4 Question Bank
// 3 Randomized Sets Per Part

const READING_PART3_SETS = [
  {
    desc: "Read the following information text and answer the questions.",
    time: 600, // 10 minutes
    passage: `
      <div class="passage-header"><strong>The Decline of the Monarch Butterfly</strong></div>
      <p>The monarch butterfly, renowned for its brilliant orange and black wings, undertakes one of the most spectacular natural migrations in the world. Every autumn, millions of these delicate insects travel from their summer breeding grounds in the United States and Canada to the mountainous fir forests of central Mexico, a journey spanning up to 3,000 miles. However, over the past two decades, scientists have recorded a staggering decline in the monarch population, prompting urgent conservation efforts.</p>
      <p>A primary driver of this decline is the loss of the monarch’s critical habitat. In North America, the expansion of industrial agriculture and urban development has severely reduced the availability of milkweed. Milkweed is the sole food source for monarch caterpillars; without it, the butterflies cannot reproduce. The widespread use of herbicides in farming has decimated milkweed populations across the Midwest, a crucial region along the monarch’s migration route.</p>
      <p>Furthermore, the overwintering habitats in Mexico are under threat. Illegal logging and forest degradation in the specific microclimates where the monarchs cluster for the winter expose the insects to freezing temperatures and winter storms. The loss of a dense forest canopy drastically reduces the environmental insulation the butterflies rely on to survive the cold months.</p>
      <p>Climate change also poses a complex threat to the monarch. Extreme weather events, such as prolonged droughts and unusually severe storms, can disrupt migration patterns and destroy breeding habitats. Additionally, temperature fluctuations may cause a misalignment between the timing of the butterflies' migration and the blooming of nectar-producing plants, depriving adult monarchs of the fuel needed for their arduous journey.</p>
      <p>In response to this crisis, a multi-national effort is underway. Conservationists are encouraging citizens to plant native milkweed in their gardens to create "waystations" for migrating monarchs. Simultaneously, international agreements aim to protect the remaining wintering forests in Mexico. While the challenges are significant, these collaborative efforts combine scientific research with community action, offering hope for the stabilization of the monarch population.</p>
    `,
    questions: [
      { q: "What remarkable behavior is the monarch butterfly famous for?", opts: ["Its ability to survive freezing temperatures", "Its extraordinarily long annual migration", "Its diverse diet of various plant species", "Its aggressive defense mechanisms"], ans: 1 },
      { q: "Where do monarch butterflies spend the winter months?", opts: ["The midwestern United States", "Canada", "Central Mexico", "South America"], ans: 2 },
      { q: "Why is milkweed vital to the survival of the monarch butterfly?", opts: ["It provides shelter from winter storms", "It is the only plant adult butterflies can land on", "It is the exclusive food source for their caterpillars", "It produces a toxin that protects them from birds"], ans: 2 },
      { q: "According to the text, what has caused a significant reduction in milkweed plants in North America?", opts: ["An overpopulation of monarch caterpillars", "A new species of invasive insect", "The use of weed-killing chemicals in large-scale farming", "Naturally occurring wildfires"], ans: 2 },
      { q: "How does illegal logging in Mexico affect the monarch butterflies?", opts: ["It destroys the milkweed they rely on for food", "It removes the forest canopy that protects them from severe winter weather", "It introduces new predators into their environment", "It forces them to migrate further south"], ans: 1 },
      { q: "How might climate change directly starve adult monarch butterflies?", opts: ["By making the air too hot for them to fly", "By causing flowers to bloom at times when the butterflies are not migrating through", "By drying out the nectar in all flowers", "By accelerating the life cycle of the caterpillar"], ans: 1 },
      { q: "What is a 'waystation' in the context of monarch conservation?", opts: ["A laboratory where butterflies are bred", "A government-protected forest in Mexico", "A planted area containing native milkweed to support migrating butterflies", "A facility that tracks butterflies using radar"], ans: 2 },
      { q: "What is the author's overall tone regarding the future of the monarch butterfly?", opts: ["Completely hopeless and pessimistic", "Cautiously optimistic due to ongoing conservation efforts", "Indifferent and strictly factual", "Angry and accusatory towards farmers"], ans: 1 },
      { q: "The word 'arduous' in the fourth paragraph is closest in meaning to:", opts: ["Simple and quick", "Unexpected", "Difficult and tiring", "Dangerous and lethal"], ans: 2 }
    ]
  },
  {
    desc: "Read the following information text and answer the questions.",
    time: 600,
    passage: `
      <div class="passage-header"><strong>The Rise of Vertical Farming</strong></div>
      <p>As the global population surges toward a projected 9 billion by 2050, traditional agriculture faces unprecedented challenges. Arable land is becoming scarce, and climate change threatens crop yields. In response, a revolutionary approach known as vertical farming has emerged. This method involves growing crops in vertically stacked layers, often integrated into other structures like skyscrapers, shipping containers, or repurposed warehouses.</p>
      <p>Vertical farming typically employs Controlled Environment Agriculture (CEA) technology. Instead of relying on unpredictable weather patterns, these indoor farms monitor and control temperature, humidity, light, and gases to create optimal growing conditions year-round. Most vertical farms utilize hydroponics, aeroponics, or aquaponics, allowing crops to thrive without traditional soil while using significantly less water than conventional field farming—sometimes up to 90% less.</p>
      <p>One of the most significant advantages of vertical farming is its potential to drastically reduce "food miles." By locating these facilities in urban centers, close to where the majority of consumers live, food can be harvested and delivered to local markets within hours. This not only ensures fresher produce but also significantly cuts down on the greenhouse gas emissions associated with transporting food across long distances.</p>
      <p>Despite its promise, the industry faces substantial hurdles. The initial capital requirement to build a highly automated vertical farm is exceptionally steep. Furthermore, the operational energy costs, primarily driven by the need for artificial LED lighting and climate control systems, are currently very high. This makes it difficult for vertical farms to be economically competitive with traditional farming for calorie-dense staple crops like wheat or corn; thus, they currently focus heavily on high-margin, fast-growing leafy greens and herbs.</p>
      <p>Proponents remain optimistic, however. They argue that as renewable energy becomes cheaper and LED technology continues to advance, the high energy costs will decline. Vertical farming may not entirely replace traditional agriculture, but it is poised to become a vital component of a diversified and resilient global food supply chain in the 21st century.</p>
    `,
    questions: [
      { q: "What global issue is vertical farming primarily attempting to address?", opts: ["The overproduction of wheat and corn", "The difficulty of feeding a growing population with limited farmland", "The lack of fresh herbs in rural areas", "The decline in traditional farming jobs"], ans: 1 },
      { q: "Where are vertical farms typically constructed?", opts: ["In rural areas with poor soil quality", "Underwater in coastal regions", "Inside indoor structures like warehouses or shipping containers", "High in the mountains to avoid flooding"], ans: 2 },
      { q: "How do vertical farms differ from traditional farms regarding water usage?", opts: ["They use significantly less water by utilizing soil-less growing methods", "They require far more water to maintain humidity", "They rely entirely on natural rainfall collected on roofs", "Water usage is roughly identical between the two methods"], ans: 0 },
      { q: "What does the term 'food miles' refer to in the text?", opts: ["The nutritional value of the food produced", "The distance food must be transported from farm to consumer", "The size of a vertical farm compared to a traditional farm", "The speed at which crops grow indoors"], ans: 1 },
      { q: "How does locating vertical farms in urban centers benefit the environment?", opts: ["It cleans the city air using plant respiration", "It reduces emissions created by long-distance transportation trucks", "It lowers the overall temperature of the city", "It uses up empty office space"], ans: 1 },
      { q: "What is currently the major financial challenge for vertical farming operations?", opts: ["The high cost of buying soil", "The expense of fighting off pests and insects", "The high energy costs for artificial lighting and climate control", "The inability to sell their produce at local markets"], ans: 2 },
      { q: "Why do most vertical farms currently focus on growing leafy greens rather than wheat?", opts: ["Wheat requires too much sunlight to grow indoors", "Leafy greens grow faster and result in a higher profit margin to offset high operating costs", "Consumers in cities do not eat wheat products", "Wheat grows too tall for stacked farming"], ans: 1 },
      { q: "What development would make vertical farming more economically viable in the future?", opts: ["An increase in the cost of traditional produce", "A decrease in the cost of renewable energy and better LED efficiency", "A ban on traditional agricultural methods", "The invention of new, cheaper types of soil"], ans: 1 },
      { q: "The word 'resilient' in the final paragraph suggests a food supply chain that is:", opts: ["Easily broken", "Able to withstand and recover from difficulties", "Completely automated", "Dependent on international trade"], ans: 1 }
    ]
  },
  {
    desc: "Read the following information text and answer the questions.",
    time: 600,
    passage: `
      <div class="passage-header"><strong>The Mechanics of Sleep and Memory</strong></div>
      <p>For decades, researchers have understood that a good night’s rest leaves people feeling refreshed, but modern neuroscience has revealed that sleep plays a highly active, crucial role in cognitive function, specifically in the consolidation of memory. We now know that sleep is not merely a period of inactivity; it is a complex biological state during which the brain is busily reorganizing and storing information gathered during waking hours.</p>
      <p>Human sleep is characterized by cycles traversing two main phases: Rapid Eye Movement (REM) sleep and non-REM (NREM) sleep. NREM sleep is further divided into lighter and deeper stages. Deep NREM sleep, often referred to as slow-wave sleep, dominates the early part of the night. It is during this phase that the brain processes declarative memories—factual information and events. Studies suggest that during slow-wave sleep, the hippocampus replays recent experiences, transferring them to the neocortex for long-term storage, effectively freeing up 'temporary' storage space for the next day.</p>
      <p>Conversely, REM sleep, which becomes more prolonged towards morning, is heavily associated with dreaming and the processing of procedural and emotional memories. Procedural memory involves the "how-to" knowledge of physical skills, like riding a bike or playing the piano. REM sleep helps refine these motor skills and integrates emotional experiences, potentially softening the emotional impact of difficult memories over time.</p>
      <p>When individuals suffer from chronic sleep deprivation, the cognitive consequences are severe. A lack of adequate slow-wave sleep severely impairs the ability to learn new factual information, as the brain's capacity to consolidate these memories is disrupted. Furthermore, insufficient REM sleep can lead to difficulties in mastering new physical tasks and can negatively impact emotional regulation, making individuals more prone to mood swings and anxiety.</p>
      <p>Therefore, pulling an "all-nighter" to study for an exam is generally counterproductive. While the student may expose themselves to more information, skipping sleep prevents the brain from performing the essential biological mechanisms required to lock that information into long-term memory. Optimal learning requires not just the intake of data, but the physiological downtime to process it.</p>
    `,
    questions: [
      { q: "What modern understanding of sleep contrasts with historical assumptions?", opts: ["Sleep requires complete physical paralysis", "Sleep is an active process of mental organization, not just a passive rest period", "Most dreaming occurs during deep NREM sleep", "Sleep is totally unnecessary for human survival"], ans: 1 },
      { q: "During which phase of sleep does the brain primarily process factual information?", opts: ["REM sleep", "Lighter stages of NREM sleep", "Deep NREM (slow-wave) sleep", "While transitioning between waking and sleeping"], ans: 2 },
      { q: "What is the role of the hippocampus during slow-wave sleep?", opts: ["It shuts down to conserve energy", "It replays memories to transfer them to long-term storage", "It generates dreams", "It controls emotional regulation"], ans: 1 },
      { q: "Which of the following is an example of procedural memory?", opts: ["Remembering a historical date", "Knowing the capital of a country", "Learning the physical steps of a dance routine", "Recalling a childhood memory"], ans: 2 },
      { q: "When does REM sleep typically occur most frequently?", opts: ["Immediately after falling asleep", "During the early part of the night", "Only during daytime naps", "More predominantly towards the morning"], ans: 3 },
      { q: "What happens if a person does not get enough REM sleep?", opts: ["They will forget the names of their family members", "They may struggle to learn physical skills and regulate their emotions", "They will fall asleep suddenly during the day", "Their brain will permanently stop transferring memories"], ans: 1 },
      { q: "Why does the author argue that studying all night without sleep is a bad idea?", opts: ["Because the student will be too tired to hold a pen", "Because the information cannot be moved into long-term memory without sleep", "Because it damages the eyes", "Because the neocortex is closed at night"], ans: 1 },
      { q: "The word 'consolidation' in the first paragraph refers to:", opts: ["The act of discarding useless information", "The process of making memories stable and permanent", "The sudden recall of a forgotten event", "The emotional feeling of sadness"], ans: 1 },
      { q: "According to the text, how does REM sleep affect difficult emotional memories?", opts: ["It makes the memories more painful over time", "It completely erases bad memories", "It may reduce the emotional intensity of those memories", "It prevents the brain from forming emotional memories at all"], ans: 2 }
    ]
  }
];

const READING_PART4_SETS = [
  {
    desc: "Read the article and the comments. Then, answer the questions.",
    time: 780, // 13 minutes
    passage: `
      <div class="passage-header"><strong>Viewpoints: Should Universities Eliminate Standardized Testing?</strong></div>
      <p>The debate over the role of standardized tests, like the SAT and ACT, in university admissions has intensified in recent years. Proponents of eliminating these tests argue that they are fundamentally inequitable. Research indicates that standardized test scores correlate strongly with family income; wealthier students often have access to expensive test-preparation tutoring and the ability to take the test multiple times. Critics argue that evaluating students primarily on their high school GPA and extracurricular activities provides a more holistic and accurate representation of their academic potential and work ethic over a four-year period, rather than their performance on a single high-stress Saturday morning.</p>
      <p>Conversely, defenders of standardized testing maintain that these exams serve as a necessary equalizer. Because high schools across the country have vastly different grading standards—a phenomenon known as "grade inflation"—a student with a 4.0 GPA from a school with lenient grading is difficult to compare against a student from a highly rigorous academy. Standardized tests, defenders argue, provide a common metric that allows colleges to objectively compare applicants nationwide. They caution that removing these tests might lead admissions officers to rely more heavily on subjective letters of recommendation or the prestige of the applicant's high school, which could inadvertently harm disadvantaged students who lack established networks.</p>
      
      <div class="diagram-box">
        <strong>Comments:</strong><br><br>
        <strong>Marcus_T:</strong> As a public school teacher, I see the stress these tests cause. We waste weeks teaching "test-taking strategies" instead of actual critical thinking. A student's four-year track record is absolutely a better indicator of their dedication. Drop the tests entirely.<br><br>
        <strong>Elena_P:</strong> I disagree. I came from an underfunded rural high school that no prestigious college had ever heard of. My high SAT score was the only way I could prove I was capable of performing at a top-tier level. If colleges didn't have that score, they would have passed over my application based on my school's zip code alone.
      </div>
    `,
    questions: [
      { q: "What is the primary argument against using standardized tests in admissions?", opts: ["They are too easy for most students", "They unfairly advantage students from wealthier families", "They take too long to grade", "They do not test math or science skills"], ans: 1 },
      { q: "How do wealthy students gain an advantage regarding these tests, according to the text?", opts: ["They can bribe the test administrators", "They are naturally smarter", "They can afford costly prep courses and multiple testing attempts", "They take a different, easier version of the test"], ans: 2 },
      { q: "What alternative metric do critics of testing prefer?", opts: ["Family background interviews", "A student's high school GPA and long-term activities", "A written essay completed at home", "Physical fitness tests"], ans: 1 },
      { q: "What is the main argument made by defenders of standardized testing?", opts: ["The tests generate revenue for universities", "They prevent grade inflation", "They provide a standardized way to compare students from different grading systems", "They test subjects not taught in high school"], ans: 2 },
      { q: "What do defenders fear will happen if tests are eliminated?", opts: ["Universities will accept too many students", "Admissions might become biased toward applicants from famous, prestigious high schools", "Students will stop trying to get good grades", "High schools will stop offering advanced classes"], ans: 1 },
      { q: "What is Marcus_T's primary complaint about standardized testing?", opts: ["It is too expensive for teachers", "It forces him to teach test strategies rather than critical thinking", "It is unfair to rural students", "It causes grade inflation"], ans: 1 },
      { q: "Elena_P's personal experience suggests that standardized tests can:", opts: ["Create unnecessary stress for students", "Provide an opportunity for students from unknown schools to stand out", "Favor students who can afford tutoring", "Be replaced entirely by strong recommendation letters"], ans: 1 },
      { q: "Based on the text, what does 'grade inflation' mean?", opts: ["Making exams physically larger", "Giving higher grades than students actually deserve", "The rising cost of college tuition", "A sudden increase in the number of high school graduates"], ans: 1 },
      { q: "How does Elena's viewpoint relate to the concerns raised by the 'defenders' in the main article?", opts: ["She completely disagrees with them", "She serves as a real-life example of their argument that tests can be an equalizer", "Her comment proves that grade inflation is real", "She ignores their concerns entirely"], ans: 1 }
    ]
  },
  {
    desc: "Read the article and the comments. Then, answer the questions.",
    time: 780,
    passage: `
      <div class="passage-header"><strong>Viewpoints: The Transition to a Cashless Society</strong></div>
      <p>Many countries are rapidly migrating toward a cashless society, a transition accelerated by consumer convenience and the rise of digital payment technologies. Advocates for a fully cashless economy argue that eliminating physical currency reduces crime, particularly tax evasion, money laundering, and traditional robbery, as digital transactions leave a traceable footprint. Furthermore, businesses benefit from not having to store, secure, or transport large amounts of physical cash, increasing efficiency and reducing operational costs. From a consumer standpoint, tapping a card or phone is faster and more hygienic than handling paper money.</p>
      <p>However, consumer rights groups and privacy advocates warn against rushing this transition. Their primary concern is financial exclusion. A significant portion of the global population is "unbanked," lacking access to bank accounts, credit cards, or smartphones. For the elderly, the homeless, or those living in poverty, cash is essential for daily survival. Mandating cashless transactions essentially locks these vulnerable groups out of participating in the economy. Additionally, privacy advocates raise alarms about the loss of anonymity. In a fully digital system, financial institutions and governments theoretically have the capability to track and analyze every purchase made by an individual, raising profound civil liberty concerns.</p>
      
      <div class="diagram-box">
        <strong>Comments:</strong><br><br>
        <strong>David_K:</strong> As a small business owner, going cashless was the best decision I made. I no longer waste hours at the bank depositing cash, my staff isn't burdened with making change, and I feel much safer not having a cash register full of bills at night. The transaction fees are worth the peace of mind.<br><br>
        <strong>Sarah_W:</strong> This sounds great until the power goes out or a banking network goes down. Last month, a software glitch at a major bank meant thousands of people couldn't buy groceries for two days because their cards were declined. We need cash as a reliable backup system. We can't be 100% dependent on servers.
      </div>
    `,
    questions: [
      { q: "According to advocates, how does a cashless society reduce crime?", opts: ["By making stealing digital devices impossible", "Because digital money is worthless to thieves", "By leaving a traceable record of all transactions, making illegal activity harder to hide", "By increasing the police presence in digital spaces"], ans: 2 },
      { q: "What is a benefit of a cashless system for businesses, as mentioned in the text?", opts: ["They don't have to hire security guards", "They avoid the need to securely store and transport physical money", "They are exempt from paying taxes", "They can charge higher prices for goods"], ans: 1 },
      { q: "What does the term 'unbanked' refer to?", opts: ["People who do not trust the government", "Banks that do not accept cash deposits", "Individuals who do not have access to formal banking services", "Businesses that only operate online"], ans: 2 },
      { q: "What is the primary concern of consumer rights groups regarding a cashless society?", opts: ["It will cause the economy to crash", "It will exclude vulnerable populations from the economy", "It will make digital transactions too expensive", "It will force people to carry too many credit cards"], ans: 1 },
      { q: "What privacy concern is associated with digital transactions?", opts: ["Hackers can easily steal physical cash", "Every purchase can be tracked and analyzed by institutions or the government", "People's faces are scanned during every purchase", "Cashiers can see bank balances"], ans: 1 },
      { q: "Why is David_K happy his business went cashless?", opts: ["He enjoys paying transaction fees", "It improved efficiency and safety for his business", "His customers demanded it", "The government forced him to do it"], ans: 1 },
      { q: "What vulnerability of a cashless system does Sarah_W highlight?", opts: ["It is too complicated for the elderly", "It excludes the homeless", "It completely fails during power outages or network failures", "It causes people to spend more money than they have"], ans: 2 },
      { q: "How do David_K and Sarah_W's views differ on digital payment systems?", opts: ["David focuses on daily operational benefits, while Sarah points out systemic vulnerabilities", "David believes it is safer from hackers, while Sarah thinks it causes tax evasion", "David is concerned about privacy, while Sarah is concerned about convenience", "They generally agree that cash is better"], ans: 0 },
      { q: "The word 'accelerated' in the first sentence is closest in meaning to:", opts: ["Stopped completely", "Sped up", "Complicated", "Slowly introduced"], ans: 1 }
    ]
  },
  {
    desc: "Read the article and the comments. Then, answer the questions.",
    time: 780,
    passage: `
      <div class="passage-header"><strong>Viewpoints: The Push for Four-Day Workweeks</strong></div>
      <p>The traditional five-day, 40-hour workweek, established nearly a century ago during the industrial era, is increasingly being challenged by advocates of a four-day model. Proponents argue that condensing the workweek to 32 hours—without a reduction in pay—dramatically improves employee well-being. Pilot programs across Europe and North America have consistently reported decreased burnout, lower stress levels, and improved work-life balance. Interestingly, many of these trials also indicate that overall productivity actually remains stable or even increases. Advocates assert that when employees are well-rested and motivated, they are more focused and waste less time on non-essential tasks during their shorter shifts.</p>
      <p>However, business leaders and skeptics point out that a universal four-day workweek is not a one-size-fits-all solution. They argue it is unfeasible for many sectors, particularly customer-facing industries like healthcare, emergency services, retail, and hospitality, which require 24/7 staffing. If a hospital or retail store shortens employee hours, they must hire additional staff to ensure coverage, significantly increasing overhead costs. Furthermore, critics caution that condensing 40 hours of expected output into 32 hours could inadvertently increase daily stress, forcing employees to work at an unsustainable, frantic pace just to meet deadlines before a long weekend.</p>
      
      <div class="diagram-box">
        <strong>Comments:</strong><br><br>
        <strong>TechLead_J:</strong> My software company switched to a Monday-Thursday schedule last year and it has been revolutionary. Retention is at an all-time high, and because people know they have a three-day weekend coming, meetings are kept short and focused. We actually get more done in four days than we ever did in five.<br><br>
        <strong>Maria_Nurse:</strong> I wish this could work for us, but in nursing, you can't just 'work faster' to condense your workload. Patients need care around the clock. If full-time nurses only work four days, the hospital has to hire 20% more staff to cover the gaps, and there's already a massive nursing shortage.
      </div>
    `,
    questions: [
      { q: "What is the key feature of the proposed four-day workweek discussed in the text?", opts: ["Working four 10-hour days", "Working fewer hours but accepting lower pay", "Working 32 hours across four days without a reduction in pay", "Working four days from home and one day in the office"], ans: 2 },
      { q: "According to proponents, what is a major benefit of the shortened workweek?", opts: ["It creates more jobs for unemployed workers", "It decreases employee burnout and improves work-life balance", "It allows companies to pay their employees less", "It eliminates the need for managers"], ans: 1 },
      { q: "How do advocates explain the finding that productivity remains stable despite fewer hours?", opts: ["Employees are secretly working on the weekends", "Well-rested employees are more focused and manage their time better", "Managers set easier goals for the staff", "Technology is doing most of the work now"], ans: 1 },
      { q: "What kind of industries do critics argue are unsuited for a four-day workweek?", opts: ["Industries that only require desk work", "Tech startups and creative agencies", "Customer-facing industries that require continuous coverage like healthcare", "Agriculture and farming"], ans: 2 },
      { q: "According to critics, how might a four-day workweek increase stress?", opts: ["By making employees worry about losing their jobs", "By forcing employees to work at a frantic pace to finish their work in less time", "By making the weekends too boring", "By increasing conflict with coworkers"], ans: 1 },
      { q: "What positive outcome does TechLead_J attribute to the new schedule?", opts: ["Higher profits for the company", "Better retention rates and more focused meetings", "The ability to hire cheaper staff", "More time to play video games"], ans: 1 },
      { q: "Why does Maria_Nurse say the four-day model won't work in her profession?", opts: ["Nurses do not want three-day weekends", "Patient care requires continuous staffing, which would necessitate hiring unavailable extra staff", "The hospital does not have the budget for higher salaries", "Nurses are paid by the hour, so they would lose money"], ans: 1 },
      { q: "What underlying theme unites the perspectives in the main article?", opts: ["The four-day workweek is universally beneficial", "The four-day workweek will inevitably fail", "The effectiveness of the four-day workweek depends heavily on the specific industry", "Technology has made the five-day workweek obsolete"], ans: 2 },
      { q: "The phrase 'one-size-fits-all solution' implies:", opts: ["A rule that applies equally well to every situation", "Clothing that is very comfortable", "A complex scientific formula", "A strategy used only in retail"], ans: 0 }
    ]
  }
];
