// CELPIP Reading Test - Parts 3 & 4 Question Bank
// 3 Randomized Sets Per Part

const READING_PART3_SETS = [
  {
    desc: "Read the following information text and answer the questions.",
    time: 600, // 10 minutes
    passage: `
      <div class="passage-header"><strong>The Decline of the Monarch Butterfly</strong></div>
      <p>The monarch butterfly, renowned for its brilliant orange and black wings, undertakes one of the most spectacular natural migrations in the world. Every autumn, millions of these delicate insects travel from their summer breeding grounds in the United States and Canada to the mountainous fir forests of central Mexico, a journey spanning up to 3,000 miles. However, over the past two decades, scientists have recorded a staggering decline in the monarch population, prompting urgent conservation efforts.</p>
      <p>A primary driver of this decline is the loss of the monarch’s critical habitat. In North America, the expansion of industrial agriculture and urban development has severely reduced the availability of milkweed. Milkweed is the sole food source for monarch caterpillars; without it, the butterflies cannot reproduce. The widespread use of herbicides in farming has decimated milkweed populations across the Midwest, a crucial region along the monarch’s migration route.</p>
      <p>Furthermore, the overwintering habitats in Mexico are under threat. Illegal logging and forest degradation in the specific microclimates where the monarchs cluster for the winter expose the insects to freezing temperatures and winter storms. The loss of a dense forest canopy drastically reduces the environmental insulation the butterflies rely on to survive the cold months.</p>
      <p>Climate change also poses a complex threat to the monarch. Extreme weather events, such as prolonged droughts and unusually severe storms, can disrupt migration patterns and destroy breeding habitats. Additionally, temperature fluctuations may cause a misalignment between the timing of the butterflies' migration and the blooming of nectar-producing plants, depriving adult monarchs of the fuel needed for their arduous journey.</p>
      <p>In response to this crisis, a multi-national effort is underway. Conservationists are encouraging citizens to plant native milkweed in their gardens to create "waystations" for migrating monarchs. Simultaneously, international agreements aim to protect the remaining wintering forests in Mexico. While the challenges are significant, these collaborative efforts combine scientific research with community action, offering hope for the stabilization of the monarch population.</p>
    `,
    questions: [
      { q: "What remarkable behavior is the monarch butterfly famous for?", opts: ["Its ability to survive freezing temperatures", "Its extraordinarily long annual migration", "Its diverse diet of various plant species", "Its aggressive defense mechanisms"], ans: 1 },
      { q: "Where do monarch butterflies spend the winter months?", opts: ["The midwestern United States", "Canada", "Central Mexico", "South America"], ans: 2 },
      { q: "Why is milkweed vital to the survival of the monarch butterfly?", opts: ["It provides shelter from winter storms", "It is the only plant adult butterflies can land on", "It is the exclusive food source for their caterpillars", "It produces a toxin that protects them from birds"], ans: 2 },
      { q: "According to the text, what has caused a significant reduction in milkweed plants in North America?", opts: ["An overpopulation of monarch caterpillars", "A new species of invasive insect", "The use of weed-killing chemicals in large-scale farming", "Naturally occurring wildfires"], ans: 2 },
      { q: "How does illegal logging in Mexico affect the monarch butterflies?", opts: ["It destroys the milkweed they rely on for food", "It removes the forest canopy that protects them from severe winter weather", "It introduces new predators into their environment", "It forces them to migrate further south"], ans: 1 },
      { q: "How might climate change directly starve adult monarch butterflies?", opts: ["By making the air too hot for them to fly", "By causing flowers to bloom at times when the butterflies are not migrating through", "By drying out the nectar in all flowers", "By accelerating the life cycle of the caterpillar"], ans: 1 },
      { q: "What is a 'waystation' in the context of monarch conservation?", opts: ["A laboratory where butterflies are bred", "A government-protected forest in Mexico", "A planted area containing native milkweed to support migrating butterflies", "A facility that tracks butterflies using radar"], ans: 2 },
      { q: "What is the author's overall tone regarding the future of the monarch butterfly?", opts: ["Completely hopeless and pessimistic", "Cautiously optimistic due to ongoing conservation efforts", "Indifferent and strictly factual", "Angry and accusatory towards farmers"], ans: 1 },
      { q: "The word 'arduous' in the fourth paragraph is closest in meaning to:", opts: ["Simple and quick", "Unexpected", "Difficult and tiring", "Dangerous and lethal"], ans: 2 }
    ]
  },
  {
    desc: "Read the following information text and answer the questions.",
    time: 600,
    passage: `
      <div class="passage-header"><strong>The Rise of Vertical Farming</strong></div>
      <p>As the global population surges toward a projected 9 billion by 2050, traditional agriculture faces unprecedented challenges. Arable land is becoming scarce, and climate change threatens crop yields. In response, a revolutionary approach known as vertical farming has emerged. This method involves growing crops in vertically stacked layers, often integrated into other structures like skyscrapers, shipping containers, or repurposed warehouses.</p>
      <p>Vertical farming typically employs Controlled Environment Agriculture (CEA) technology. Instead of relying on unpredictable weather patterns, these indoor farms monitor and control temperature, humidity, light, and gases to create optimal growing conditions year-round. Most vertical farms utilize hydroponics, aeroponics, or aquaponics, allowing crops to thrive without traditional soil while using significantly less water than conventional field farming—sometimes up to 90% less.</p>
      <p>One of the most significant advantages of vertical farming is its potential to drastically reduce "food miles." By locating these facilities in urban centers, close to where the majority of consumers live, food can be harvested and delivered to local markets within hours. This not only ensures fresher produce but also significantly cuts down on the greenhouse gas emissions associated with transporting food across long distances.</p>
      <p>Despite its promise, the industry faces substantial hurdles. The initial capital requirement to build a highly automated vertical farm is exceptionally steep. Furthermore, the operational energy costs, primarily driven by the need for artificial LED lighting and climate control systems, are currently very high. This makes it difficult for vertical farms to be economically competitive with traditional farming for calorie-dense staple crops like wheat or corn; thus, they currently focus heavily on high-margin, fast-growing leafy greens and herbs.</p>
      <p>Proponents remain optimistic, however. They argue that as renewable energy becomes cheaper and LED technology continues to advance, the high energy costs will decline. Vertical farming may not entirely replace traditional agriculture, but it is poised to become a vital component of a diversified and resilient global food supply chain in the 21st century.</p>
    `,
    questions: [
      { q: "What global issue is vertical farming primarily attempting to address?", opts: ["The overproduction of wheat and corn", "The difficulty of feeding a growing population with limited farmland", "The lack of fresh herbs in rural areas", "The decline in traditional farming jobs"], ans: 1 },
      { q: "Where are vertical farms typically constructed?", opts: ["In rural areas with poor soil quality", "Underwater in coastal regions", "Inside indoor structures like warehouses or shipping containers", "High in the mountains to avoid flooding"], ans: 2 },
      { q: "How do vertical farms differ from traditional farms regarding water usage?", opts: ["They use significantly less water by utilizing soil-less growing methods", "They require far more water to maintain humidity", "They rely entirely on natural rainfall collected on roofs", "Water usage is roughly identical between the two methods"], ans: 0 },
      { q: "What does the term 'food miles' refer to in the text?", opts: ["The nutritional value of the food produced", "The distance food must be transported from farm to consumer", "The size of a vertical farm compared to a traditional farm", "The speed at which crops grow indoors"], ans: 1 },
      { q: "How does locating vertical farms in urban centers benefit the environment?", opts: ["It cleans the city air using plant respiration", "It reduces emissions created by long-distance transportation trucks", "It lowers the overall temperature of the city", "It uses up empty office space"], ans: 1 },
      { q: "What is currently the major financial challenge for vertical farming operations?", opts: ["The high cost of buying soil", "The expense of fighting off pests and insects", "The high energy costs for artificial lighting and climate control", "The inability to sell their produce at local markets"], ans: 2 },
      { q: "Why do most vertical farms currently focus on growing leafy greens rather than wheat?", opts: ["Wheat requires too much sunlight to grow indoors", "Leafy greens grow faster and result in a higher profit margin to offset high operating costs", "Consumers in cities do not eat wheat products", "Wheat grows too tall for stacked farming"], ans: 1 },
      { q: "What development would make vertical farming more economically viable in the future?", opts: ["An increase in the cost of traditional produce", "A decrease in the cost of renewable energy and better LED efficiency", "A ban on traditional agricultural methods", "The invention of new, cheaper types of soil"], ans: 1 },
      { q: "The word 'resilient' in the final paragraph suggests a food supply chain that is:", opts: ["Easily broken", "Able to withstand and recover from difficulties", "Completely automated", "Dependent on international trade"], ans: 1 }
    ]
  },
  {
    desc: "Read the following information text and answer the questions.",
    time: 600,
    passage: `
      <div class="passage-header"><strong>The Mechanics of Sleep and Memory</strong></div>
      <p>For decades, researchers have understood that a good night’s rest leaves people feeling refreshed, but modern neuroscience has revealed that sleep plays a highly active, crucial role in cognitive function, specifically in the consolidation of memory. We now know that sleep is not merely a period of inactivity; it is a complex biological state during which the brain is busily reorganizing and storing information gathered during waking hours.</p>
      <p>Human sleep is characterized by cycles traversing two main phases: Rapid Eye Movement (REM) sleep and non-REM (NREM) sleep. NREM sleep is further divided into lighter and deeper stages. Deep NREM sleep, often referred to as slow-wave sleep, dominates the early part of the night. It is during this phase that the brain processes declarative memories—factual information and events. Studies suggest that during slow-wave sleep, the hippocampus replays recent experiences, transferring them to the neocortex for long-term storage, effectively freeing up 'temporary' storage space for the next day.</p>
      <p>Conversely, REM sleep, which becomes more prolonged towards morning, is heavily associated with dreaming and the processing of procedural and emotional memories. Procedural memory involves the "how-to" knowledge of physical skills, like riding a bike or playing the piano. REM sleep helps refine these motor skills and integrates emotional experiences, potentially softening the emotional impact of difficult memories over time.</p>
      <p>When individuals suffer from chronic sleep deprivation, the cognitive consequences are severe. A lack of adequate slow-wave sleep severely impairs the ability to learn new factual information, as the brain's capacity to consolidate these memories is disrupted. Furthermore, insufficient REM sleep can lead to difficulties in mastering new physical tasks and can negatively impact emotional regulation, making individuals more prone to mood swings and anxiety.</p>
      <p>Therefore, pulling an "all-nighter" to study for an exam is generally counterproductive. While the student may expose themselves to more information, skipping sleep prevents the brain from performing the essential biological mechanisms required to lock that information into long-term memory. Optimal learning requires not just the intake of data, but the physiological downtime to process it.</p>
    `,
    questions: [
      { q: "What modern understanding of sleep contrasts with historical assumptions?", opts: ["Sleep requires complete physical paralysis", "Sleep is an active process of mental organization, not just a passive rest period", "Most dreaming occurs during deep NREM sleep", "Sleep is totally unnecessary for human survival"], ans: 1 },
      { q: "During which phase of sleep does the brain primarily process factual information?", opts: ["REM sleep", "Lighter stages of NREM sleep", "Deep NREM (slow-wave) sleep", "While transitioning between waking and sleeping"], ans: 2 },
      { q: "What is the role of the hippocampus during slow-wave sleep?", opts: ["It shuts down to conserve energy", "It replays memories to transfer them to long-term storage", "It generates dreams", "It controls emotional regulation"], ans: 1 },
      { q: "Which of the following is an example of procedural memory?", opts: ["Remembering a historical date", "Knowing the capital of a country", "Learning the physical steps of a dance routine", "Recalling a childhood memory"], ans: 2 },
      { q: "When does REM sleep typically occur most frequently?", opts: ["Immediately after falling asleep", "During the early part of the night", "Only during daytime naps", "More predominantly towards the morning"], ans: 3 },
      { q: "What happens if a person does not get enough REM sleep?", opts: ["They will forget the names of their family members", "They may struggle to learn physical skills and regulate their emotions", "They will fall asleep suddenly during the day", "Their brain will permanently stop transferring memories"], ans: 1 },
      { q: "Why does the author argue that studying all night without sleep is a bad idea?", opts: ["Because the student will be too tired to hold a pen", "Because the information cannot be moved into long-term memory without sleep", "Because it damages the eyes", "Because the neocortex is closed at night"], ans: 1 },
      { q: "The word 'consolidation' in the first paragraph refers to:", opts: ["The act of discarding useless information", "The process of making memories stable and permanent", "The sudden recall of a forgotten event", "The emotional feeling of sadness"], ans: 1 },
      { q: "According to the text, how does REM sleep affect difficult emotional memories?", opts: ["It makes the memories more painful over time", "It completely erases bad memories", "It may reduce the emotional intensity of those memories", "It prevents the brain from forming emotional memories at all"], ans: 2 }
    ]
  },
  {
    desc: "Read the following information text and answer the questions.",
    time: 600,
    passage: `
      <div class="passage-header"><strong>The Narwhal: Unicorn of the Sea</strong></div>
      <p>The narwhal, sometimes called the "unicorn of the sea," is a medium-sized toothed whale found in the Arctic waters of Canada, Greenland, Norway, and Russia. Its scientific name, Monodon monoceros, is Latin for "one tooth, one horn" — a reference to its most distinguishing feature: a long, spiraling tusk that can grow up to three metres in length. The tusk is actually a modified canine tooth that grows through the upper lip, almost always on the left side, and is found primarily in adult males, though some females develop a shorter version. Despite centuries of fascination, the function of the narwhal's iconic tusk remains one of the sea's great unsolved mysteries. Scientists have proposed that it may be used in displays of dominance, in sensing changes in water temperature and salinity, or in locating prey beneath the ice.</p>
      <p>Narwhals are highly social animals that spend their lives in Arctic seas, migrating seasonally between summer feeding grounds and winter ice-covered areas. They typically travel in groups called pods, ranging from a handful of individuals to herds of hundreds. During winter, narwhals survive under sea ice by breathing through natural openings called leads. Remarkably, narwhals can dive to depths of over fifteen hundred metres in search of food, making them one of the deepest-diving marine mammals in the world. Their diet consists primarily of Greenland halibut, Arctic cod, squid, and shrimp.</p>
      <p>Although narwhals have been hunted for centuries by Indigenous communities in Canada and Greenland — who prize the tusk, skin, and blubber for cultural and nutritional purposes — the species now faces mounting pressures from climate change. Warming Arctic temperatures are reducing sea ice at an unprecedented rate, fundamentally altering the marine environment these animals depend on. Loss of sea ice affects the distribution of fish and invertebrates narwhals feed on and allows new predators, including killer whales, to penetrate previously inaccessible Arctic regions.</p>
      <p>Conservation organizations and scientists are working to better understand narwhal population dynamics by deploying satellite tags on captured animals. These tracking studies, conducted jointly by Canadian and Greenlandic researchers, have revealed that narwhals follow remarkably consistent migration routes year after year. While the narwhal is currently listed as "Least Concern" on the IUCN Red List, researchers caution that climate change represents a long-term existential threat — and that the species' limited range and specialized habitat make it particularly vulnerable to rapid environmental shifts.</p>
    `,
    questions: [
      { q: "What does the narwhal's scientific name Monodon monoceros mean?", opts: ["Arctic whale with two teeth", "One tooth, one horn", "Ocean unicorn of the north", "Deep-diving horned mammal"], ans: 1 },
      { q: "In which sex is the narwhal's tusk most commonly found?", opts: ["Only in females", "Equally in both males and females", "Primarily in adult males", "Only in juvenile narwhals"], ans: 2 },
      { q: "What is one proposed function of the narwhal's tusk?", opts: ["It is used to break through thick sea ice", "It helps the animal steer during deep dives", "It may be used to sense changes in water temperature and salinity", "It is primarily used to fight off killer whales"], ans: 2 },
      { q: "How deep can narwhals dive in search of food?", opts: ["Up to five hundred metres", "Up to one thousand metres", "Over fifteen hundred metres", "Up to three thousand metres"], ans: 2 },
      { q: "How has climate change most directly affected narwhals?", opts: ["Rising temperatures have reduced their body size", "Melting sea ice alters their food sources and allows new predators into their range", "Warmer winters have forced them to migrate further south permanently", "Increased human activity has disrupted their migration routes"], ans: 1 },
      { q: "What have satellite tagging studies revealed about narwhal migration?", opts: ["They change routes unpredictably every year", "They migrate further than any other marine mammal", "They follow consistent migration routes year after year", "Their routes have shifted dramatically in recent years"], ans: 2 },
      { q: "What is the narwhal's current status on the IUCN Red List?", opts: ["Critically Endangered", "Endangered", "Vulnerable", "Least Concern"], ans: 3 },
      { q: "What does the text say about narwhals breathing under sea ice?", opts: ["They hold their breath for up to an hour", "They surface through natural openings called leads", "They use their tusks to pierce through the ice", "They migrate south before the ice forms"], ans: 1 },
      { q: "The word 'unprecedented' in the third paragraph means:", opts: ["Expected and predictable", "Slower than previously measured", "Never having happened before at this scale", "Reversible and temporary"], ans: 2 }
    ]
  },
  {
    desc: "Read the following information text and answer the questions.",
    time: 600,
    passage: `
      <div class="passage-header"><strong>Canada's Camping Culture</strong></div>
      <p>Canada is home to some of the most spectacular natural landscapes on earth, and camping has long been a cornerstone of Canadian outdoor culture. With over forty national parks and more than one thousand provincial parks spanning ten provinces and three territories, Canada offers camping experiences for every level of enthusiasm — from wilderness backcountry expeditions to family-friendly serviced campgrounds with electricity hookups and flush toilets. According to Statistics Canada, approximately one-third of Canadian households own camping equipment, and roughly one in four Canadians camps at least once each year.</p>
      <p>The diversity of camping options reflects the vast range of Canada's geography. In British Columbia, campers can pitch tents on Pacific beaches or in temperate rainforests. Alberta's Rocky Mountain parks, including Banff and Jasper, are consistently ranked among the most visited campgrounds in North America, drawing hundreds of thousands of visitors each summer. In Ontario, Algonquin Provincial Park offers world-famous canoe-camping routes weaving through thousands of lakes and rivers. Further east, the coastal provinces offer dramatic oceanfront camping in parks like Cape Breton Highlands in Nova Scotia and Fundy Trail in New Brunswick.</p>
      <p>Camping gear has evolved considerably in recent decades. Modern campers benefit from ultralight backpacking tents weighing under one kilogram, portable solar-powered lanterns, and water filtration systems that purify a litre of water in under a minute. For families and casual campers who prefer more comfort, the rise of "glamping" — glamorous camping — has introduced luxury tent cabins, heated platform tents, and high-end outfitted sites where bedding, kitchenware, and firewood are all provided. This segment of the market has grown rapidly, with several glamping operations across Canada now offering accommodations that rival boutique hotels in comfort.</p>
      <p>Despite its popularity, camping comes with environmental responsibilities. "Leave No Trace" principles, now widely taught in Canadian outdoor education programs, emphasize packing out all garbage, avoiding damage to vegetation, using established fire rings, and respecting wildlife by storing food properly. Parks Canada and provincial park authorities have also introduced fire restriction protocols to reduce the risk of wildfires, which have increased in frequency and severity as a result of prolonged droughts and climate change.</p>
    `,
    questions: [
      { q: "Approximately what fraction of Canadian households own camping equipment?", opts: ["About one-quarter", "About one-third", "About one-half", "About two-thirds"], ans: 1 },
      { q: "Which park is known for famous canoe-camping routes?", opts: ["Banff National Park", "Cape Breton Highlands", "Algonquin Provincial Park", "Jasper National Park"], ans: 2 },
      { q: "What advancement in camping gear is mentioned in the text?", opts: ["Camping gear has become significantly cheaper", "Modern equipment is heavier but more durable", "Gear now includes ultralight tents, solar lanterns, and fast water filtration", "Traditional gear has been replaced entirely by electronic devices"], ans: 2 },
      { q: "What is 'glamping'?", opts: ["An extreme form of wilderness camping with no equipment", "A form of camping that combines luxury amenities with an outdoor setting", "A camping style exclusive to cold climate environments", "A group camping event organized by outdoor clubs"], ans: 1 },
      { q: "How many national parks does Canada have, according to the passage?", opts: ["Over twenty", "Over thirty", "Over forty", "Over sixty"], ans: 2 },
      { q: "What is the purpose of 'Leave No Trace' principles?", opts: ["To encourage campers to explore unmarked wilderness areas", "To promote responsible camping that minimizes environmental impact", "To restrict camping to designated national parks only", "To help campers avoid getting lost"], ans: 1 },
      { q: "Why have fire restriction protocols been introduced in Canadian parks?", opts: ["To reduce the number of campers in sensitive ecosystems", "Because campfires are now illegal across all Canadian parks", "To lower the risk of wildfires, which have increased due to drought and climate change", "To save firewood for winter survival emergencies"], ans: 2 },
      { q: "Where can campers find oceanfront camping in Atlantic Canada, according to the text?", opts: ["Algonquin Provincial Park and Banff National Park", "Cape Breton Highlands in Nova Scotia and Fundy Trail in New Brunswick", "Prince Edward Island and Labrador", "Riding Mountain and Kejimkujik National Parks"], ans: 1 },
      { q: "The word 'cornerstone' in the first paragraph suggests that camping is:", opts: ["A rarely practised and declining tradition in Canada", "A fundamental and central part of Canadian culture", "A recent trend that has grown rapidly in the past decade", "A controversial activity with both supporters and opponents"], ans: 1 }
    ]
  },
  {
    desc: "Read the following information text and answer the questions.",
    time: 600,
    passage: `
      <div class="passage-header"><strong>The Beaver: Canada's Industrious Icon</strong></div>
      <p>The North American beaver (Castor canadensis) is Canada's largest rodent and, since 1975, its official national animal — a distinction that reflects both the beaver's historical importance to the country's development and its enduring role in Canadian ecosystems. An adult beaver typically weighs between sixteen and thirty kilograms and measures up to one hundred and twenty centimetres from nose to tail. Beavers are highly adapted for aquatic life: their sleek, waterproofed fur repels water, their webbed hind feet act as paddles, and their broad, flat tail functions as a rudder and as a warning signal — slapping the water's surface when danger is sensed.</p>
      <p>Beavers are nature's most accomplished engineers. They fell trees using their large, ever-growing incisors — which are coated with hardened orange enamel containing iron — and use the logs and branches to construct dams across streams and rivers. These dams slow water flow and create the shallow ponds beavers need to protect their lodges from predators, while also maintaining underwater entrances that are difficult for predators to access. A single beaver pair and their offspring can build a dam several metres long in just a few days, and a well-maintained dam can last for decades.</p>
      <p>The ecological impact of beaver activity is profound. By creating wetlands, beaver dams raise the water table, reduce drought stress on surrounding vegetation, and filter agricultural runoff and pollutants from the water. These constructed wetlands become thriving habitats for dozens of other species, including waterfowl, fish, amphibians, insects, and mammals. Ecologists increasingly refer to the beaver as a "keystone species" — one whose presence or absence disproportionately shapes the health of the entire ecosystem.</p>
      <p>Historically, the beaver played a defining role in the establishment of Canada as a nation. European demand for beaver pelts — used primarily to make fashionable felt hats — drove the fur trade that opened Canada's interior to European exploration and eventually led to the formation of commercial and political institutions, including the Hudson's Bay Company, founded in 1670. So central was the beaver to Canadian commerce that it appeared on the first Canadian postage stamp, issued in 1851.</p>
    `,
    questions: [
      { q: "When did the beaver become Canada's official national animal?", opts: ["1851", "1867", "1975", "1990"], ans: 2 },
      { q: "What is the function of the beaver's flat tail?", opts: ["Storing fat for winter survival", "Acting as a rudder and warning signal", "Helping it climb trees to access food", "Regulating body temperature in cold water"], ans: 1 },
      { q: "What makes the beaver's incisors particularly strong?", opts: ["They are made of a double layer of ordinary enamel", "They are coated with iron-containing orange enamel", "They regrow from a harder second set after the first year", "They are reinforced with calcium from the beaver's diet"], ans: 1 },
      { q: "Why do beavers build dams, according to the text?", opts: ["To redirect rivers toward their food sources", "To create ponds that protect their lodges and underwater entrances from predators", "To prevent flooding of their surrounding territory", "To mark territorial boundaries from other beaver families"], ans: 1 },
      { q: "What does the term 'keystone species' mean in the context of the passage?", opts: ["A species that is the largest in its ecosystem", "A species whose presence or absence significantly affects the health of the entire ecosystem", "A species that builds structures used by other animals", "A species that was once endangered but has recovered"], ans: 1 },
      { q: "How do beaver-created wetlands benefit the surrounding environment?", opts: ["They prevent the spread of invasive plants", "They raise the water table, filter pollutants, and create habitat for many species", "They reduce soil erosion along riverbanks only", "They increase the flow speed of rivers downstream"], ans: 1 },
      { q: "What historically drove European exploration of Canada's interior?", opts: ["The search for gold and silver deposits", "The need to establish military outposts", "European demand for beaver pelts used in hat-making", "The desire to establish permanent farming settlements"], ans: 2 },
      { q: "What significance did the beaver have in the postal history of Canada?", opts: ["It was featured on the first Canadian dollar coin", "It appeared on the first Canadian postage stamp in 1851", "It was chosen as the symbol of the Hudson's Bay Company in 1670", "It was depicted on the original Confederation documents"], ans: 1 },
      { q: "The word 'disproportionately' in the third paragraph means:", opts: ["In equal proportion to other species", "To a lesser degree than would be expected", "To a greater degree than would be expected given the species' size or number", "In a way that is difficult to measure scientifically"], ans: 2 }
    ]
  }
];

const READING_PART4_SETS = [
  {
    desc: "Read the article and the comments. Then, answer the questions.",
    time: 780, // 13 minutes
    passage: `
      <div class="passage-header"><strong>Viewpoints: Should Universities Eliminate Standardized Testing?</strong></div>
      <p>The debate over the role of standardized tests, like the SAT and ACT, in university admissions has intensified in recent years. Proponents of eliminating these tests argue that they are fundamentally inequitable. Research indicates that standardized test scores correlate strongly with family income; wealthier students often have access to expensive test-preparation tutoring and the ability to take the test multiple times. Critics argue that evaluating students primarily on their high school GPA and extracurricular activities provides a more holistic and accurate representation of their academic potential and work ethic over a four-year period, rather than their performance on a single high-stress Saturday morning.</p>
      <p>Conversely, defenders of standardized testing maintain that these exams serve as a necessary equalizer. Because high schools across the country have vastly different grading standards—a phenomenon known as "grade inflation"—a student with a 4.0 GPA from a school with lenient grading is difficult to compare against a student from a highly rigorous academy. Standardized tests, defenders argue, provide a common metric that allows colleges to objectively compare applicants nationwide. They caution that removing these tests might lead admissions officers to rely more heavily on subjective letters of recommendation or the prestige of the applicant's high school, which could inadvertently harm disadvantaged students who lack established networks.</p>
      
      <div class="diagram-box">
        <strong>Comments:</strong><br><br>
        <strong>Marcus_T:</strong> As a public school teacher, I see the stress these tests cause. We waste weeks teaching "test-taking strategies" instead of actual critical thinking. A student's four-year track record is absolutely a better indicator of their dedication. Drop the tests entirely.<br><br>
        <strong>Elena_P:</strong> I disagree. I came from an underfunded rural high school that no prestigious college had ever heard of. My high SAT score was the only way I could prove I was capable of performing at a top-tier level. If colleges didn't have that score, they would have passed over my application based on my school's zip code alone.
      </div>
    `,
    questions: [
      { q: "What is the primary argument against using standardized tests in admissions?", opts: ["They are too easy for most students", "They unfairly advantage students from wealthier families", "They take too long to grade", "They do not test math or science skills"], ans: 1 },
      { q: "How do wealthy students gain an advantage regarding these tests, according to the text?", opts: ["They can bribe the test administrators", "They are naturally smarter", "They can afford costly prep courses and multiple testing attempts", "They take a different, easier version of the test"], ans: 2 },
      { q: "What alternative metric do critics of testing prefer?", opts: ["Family background interviews", "A student's high school GPA and long-term activities", "A written essay completed at home", "Physical fitness tests"], ans: 1 },
      { q: "What is the main argument made by defenders of standardized testing?", opts: ["The tests generate revenue for universities", "They prevent grade inflation", "They provide a standardized way to compare students from different grading systems", "They test subjects not taught in high school"], ans: 2 },
      { q: "What do defenders fear will happen if tests are eliminated?", opts: ["Universities will accept too many students", "Admissions might become biased toward applicants from famous, prestigious high schools", "Students will stop trying to get good grades", "High schools will stop offering advanced classes"], ans: 1 },
      { q: "What is Marcus_T's primary complaint about standardized testing?", opts: ["It is too expensive for teachers", "It forces him to teach test strategies rather than critical thinking", "It is unfair to rural students", "It causes grade inflation"], ans: 1 },
      { q: "Elena_P's personal experience suggests that standardized tests can:", opts: ["Create unnecessary stress for students", "Provide an opportunity for students from unknown schools to stand out", "Favor students who can afford tutoring", "Be replaced entirely by strong recommendation letters"], ans: 1 },
      { q: "Based on the text, what does 'grade inflation' mean?", opts: ["Making exams physically larger", "Giving higher grades than students actually deserve", "The rising cost of college tuition", "A sudden increase in the number of high school graduates"], ans: 1 },
      { q: "How does Elena's viewpoint relate to the concerns raised by the 'defenders' in the main article?", opts: ["She completely disagrees with them", "She serves as a real-life example of their argument that tests can be an equalizer", "Her comment proves that grade inflation is real", "She ignores their concerns entirely"], ans: 1 }
    ]
  },
  {
    desc: "Read the article and the comments. Then, answer the questions.",
    time: 780,
    passage: `
      <div class="passage-header"><strong>Viewpoints: The Transition to a Cashless Society</strong></div>
      <p>Many countries are rapidly migrating toward a cashless society, a transition accelerated by consumer convenience and the rise of digital payment technologies. Advocates for a fully cashless economy argue that eliminating physical currency reduces crime, particularly tax evasion, money laundering, and traditional robbery, as digital transactions leave a traceable footprint. Furthermore, businesses benefit from not having to store, secure, or transport large amounts of physical cash, increasing efficiency and reducing operational costs. From a consumer standpoint, tapping a card or phone is faster and more hygienic than handling paper money.</p>
      <p>However, consumer rights groups and privacy advocates warn against rushing this transition. Their primary concern is financial exclusion. A significant portion of the global population is "unbanked," lacking access to bank accounts, credit cards, or smartphones. For the elderly, the homeless, or those living in poverty, cash is essential for daily survival. Mandating cashless transactions essentially locks these vulnerable groups out of participating in the economy. Additionally, privacy advocates raise alarms about the loss of anonymity. In a fully digital system, financial institutions and governments theoretically have the capability to track and analyze every purchase made by an individual, raising profound civil liberty concerns.</p>
      
      <div class="diagram-box">
        <strong>Comments:</strong><br><br>
        <strong>David_K:</strong> As a small business owner, going cashless was the best decision I made. I no longer waste hours at the bank depositing cash, my staff isn't burdened with making change, and I feel much safer not having a cash register full of bills at night. The transaction fees are worth the peace of mind.<br><br>
        <strong>Sarah_W:</strong> This sounds great until the power goes out or a banking network goes down. Last month, a software glitch at a major bank meant thousands of people couldn't buy groceries for two days because their cards were declined. We need cash as a reliable backup system. We can't be 100% dependent on servers.
      </div>
    `,
    questions: [
      { q: "According to advocates, how does a cashless society reduce crime?", opts: ["By making stealing digital devices impossible", "Because digital money is worthless to thieves", "By leaving a traceable record of all transactions, making illegal activity harder to hide", "By increasing the police presence in digital spaces"], ans: 2 },
      { q: "What is a benefit of a cashless system for businesses, as mentioned in the text?", opts: ["They don't have to hire security guards", "They avoid the need to securely store and transport physical money", "They are exempt from paying taxes", "They can charge higher prices for goods"], ans: 1 },
      { q: "What does the term 'unbanked' refer to?", opts: ["People who do not trust the government", "Banks that do not accept cash deposits", "Individuals who do not have access to formal banking services", "Businesses that only operate online"], ans: 2 },
      { q: "What is the primary concern of consumer rights groups regarding a cashless society?", opts: ["It will cause the economy to crash", "It will exclude vulnerable populations from the economy", "It will make digital transactions too expensive", "It will force people to carry too many credit cards"], ans: 1 },
      { q: "What privacy concern is associated with digital transactions?", opts: ["Hackers can easily steal physical cash", "Every purchase can be tracked and analyzed by institutions or the government", "People's faces are scanned during every purchase", "Cashiers can see bank balances"], ans: 1 },
      { q: "Why is David_K happy his business went cashless?", opts: ["He enjoys paying transaction fees", "It improved efficiency and safety for his business", "His customers demanded it", "The government forced him to do it"], ans: 1 },
      { q: "What vulnerability of a cashless system does Sarah_W highlight?", opts: ["It is too complicated for the elderly", "It excludes the homeless", "It completely fails during power outages or network failures", "It causes people to spend more money than they have"], ans: 2 },
      { q: "How do David_K and Sarah_W's views differ on digital payment systems?", opts: ["David focuses on daily operational benefits, while Sarah points out systemic vulnerabilities", "David believes it is safer from hackers, while Sarah thinks it causes tax evasion", "David is concerned about privacy, while Sarah is concerned about convenience", "They generally agree that cash is better"], ans: 0 },
      { q: "The word 'accelerated' in the first sentence is closest in meaning to:", opts: ["Stopped completely", "Sped up", "Complicated", "Slowly introduced"], ans: 1 }
    ]
  },
  {
    desc: "Read the article and the comments. Then, answer the questions.",
    time: 780,
    passage: `
      <div class="passage-header"><strong>Viewpoints: The Push for Four-Day Workweeks</strong></div>
      <p>The traditional five-day, 40-hour workweek, established nearly a century ago during the industrial era, is increasingly being challenged by advocates of a four-day model. Proponents argue that condensing the workweek to 32 hours—without a reduction in pay—dramatically improves employee well-being. Pilot programs across Europe and North America have consistently reported decreased burnout, lower stress levels, and improved work-life balance. Interestingly, many of these trials also indicate that overall productivity actually remains stable or even increases. Advocates assert that when employees are well-rested and motivated, they are more focused and waste less time on non-essential tasks during their shorter shifts.</p>
      <p>However, business leaders and skeptics point out that a universal four-day workweek is not a one-size-fits-all solution. They argue it is unfeasible for many sectors, particularly customer-facing industries like healthcare, emergency services, retail, and hospitality, which require 24/7 staffing. If a hospital or retail store shortens employee hours, they must hire additional staff to ensure coverage, significantly increasing overhead costs. Furthermore, critics caution that condensing 40 hours of expected output into 32 hours could inadvertently increase daily stress, forcing employees to work at an unsustainable, frantic pace just to meet deadlines before a long weekend.</p>
      
      <div class="diagram-box">
        <strong>Comments:</strong><br><br>
        <strong>TechLead_J:</strong> My software company switched to a Monday-Thursday schedule last year and it has been revolutionary. Retention is at an all-time high, and because people know they have a three-day weekend coming, meetings are kept short and focused. We actually get more done in four days than we ever did in five.<br><br>
        <strong>Maria_Nurse:</strong> I wish this could work for us, but in nursing, you can't just 'work faster' to condense your workload. Patients need care around the clock. If full-time nurses only work four days, the hospital has to hire 20% more staff to cover the gaps, and there's already a massive nursing shortage.
      </div>
    `,
    questions: [
      { q: "What is the key feature of the proposed four-day workweek discussed in the text?", opts: ["Working four 10-hour days", "Working fewer hours but accepting lower pay", "Working 32 hours across four days without a reduction in pay", "Working four days from home and one day in the office"], ans: 2 },
      { q: "According to proponents, what is a major benefit of the shortened workweek?", opts: ["It creates more jobs for unemployed workers", "It decreases employee burnout and improves work-life balance", "It allows companies to pay their employees less", "It eliminates the need for managers"], ans: 1 },
      { q: "How do advocates explain the finding that productivity remains stable despite fewer hours?", opts: ["Employees are secretly working on the weekends", "Well-rested employees are more focused and manage their time better", "Managers set easier goals for the staff", "Technology is doing most of the work now"], ans: 1 },
      { q: "What kind of industries do critics argue are unsuited for a four-day workweek?", opts: ["Industries that only require desk work", "Tech startups and creative agencies", "Customer-facing industries that require continuous coverage like healthcare", "Agriculture and farming"], ans: 2 },
      { q: "According to critics, how might a four-day workweek increase stress?", opts: ["By making employees worry about losing their jobs", "By forcing employees to work at a frantic pace to finish their work in less time", "By making the weekends too boring", "By increasing conflict with coworkers"], ans: 1 },
      { q: "What positive outcome does TechLead_J attribute to the new schedule?", opts: ["Higher profits for the company", "Better retention rates and more focused meetings", "The ability to hire cheaper staff", "More time to play video games"], ans: 1 },
      { q: "Why does Maria_Nurse say the four-day model won't work in her profession?", opts: ["Nurses do not want three-day weekends", "Patient care requires continuous staffing, which would necessitate hiring unavailable extra staff", "The hospital does not have the budget for higher salaries", "Nurses are paid by the hour, so they would lose money"], ans: 1 },
      { q: "What underlying theme unites the perspectives in the main article?", opts: ["The four-day workweek is universally beneficial", "The four-day workweek will inevitably fail", "The effectiveness of the four-day workweek depends heavily on the specific industry", "Technology has made the five-day workweek obsolete"], ans: 2 },
      { q: "The phrase 'one-size-fits-all solution' implies:", opts: ["A rule that applies equally well to every situation", "Clothing that is very comfortable", "A complex scientific formula", "A strategy used only in retail"], ans: 0 }
    ]
  },
  {
    desc: "Read the article and the comments. Then, answer the questions.",
    time: 780,
    passage: `
      <div class="passage-header"><strong>Viewpoints: Is Remote Work Here to Stay?</strong></div>
      <p>The shift to remote work that began as an emergency pandemic response has now settled into a permanent feature of many workplaces — but whether it represents genuine progress or a regression in workplace culture remains fiercely debated. Proponents argue that the past several years have conclusively demonstrated that knowledge workers can perform their roles effectively from home. Surveys consistently show that remote workers report higher job satisfaction, and many would consider leaving an employer that mandates full-time office return. Advocates also point to the democratizing effect of remote work: without geographic restrictions, employers can recruit talent from across the country, and employees can choose to live in more affordable regions without sacrificing career prospects.</p>
      <p>Critics, however, warn that the apparent productivity gains of remote work are incomplete. Karen Lopez, a human resources consultant specializing in organizational culture, argues that remote work systematically erodes the informal mentoring and social learning that happens when junior employees observe and interact with experienced colleagues in a shared environment. "The things that can't be measured on a productivity dashboard — the hallway conversation, the observation of how a senior person handles a difficult client — those are the things that build careers," she says. Lopez also points to studies suggesting that while individual task completion rates improve remotely, collaborative creativity and complex problem-solving decline significantly when teams are not physically co-located.</p>

      <div class="diagram-box">
        <strong>Comments:</strong><br><br>
        <strong>Victor_T:</strong> I've been fully remote for three years and I'm more productive than I've ever been. I live in Moncton now instead of Toronto. My mortgage is half what it used to be, and I'm spending saved commute time with my kids. Anyone who says remote work doesn't perform hasn't looked at the actual data from the last five years.<br><br>
        <strong>Elena_M:</strong> I managed a team that went fully remote and I watched junior hires struggle in ways that simply wouldn't have happened in an office. They couldn't read the room in meetings, they didn't know how to push back constructively, and two of them left because they felt invisible. Remote work is great for experienced professionals. For people early in their careers, it can be quietly devastating.
      </div>
    `,
    questions: [
      { q: "What do surveys suggest about remote workers' attitudes toward mandatory office returns?", opts: ["Most remote workers are eager to return full-time", "Many remote workers would consider leaving an employer that requires full-time office attendance", "Remote workers prefer a three-day office schedule", "Remote workers are indifferent to whether they work from home or the office"], ans: 1 },
      { q: "What 'democratizing effect' of remote work do advocates mention?", opts: ["All employees earn the same salary regardless of location", "Employees can work from any country in the world", "Geographic restrictions are removed, allowing talent recruitment across the country and more affordable living", "Managers and employees now have equal say in company decisions"], ans: 2 },
      { q: "What does Karen Lopez argue is the main cost of remote work?", opts: ["Companies spend more money on digital tools", "Employees work longer hours than they would in the office", "Informal mentoring and social learning are systematically lost", "Remote teams produce lower quality individual work"], ans: 2 },
      { q: "According to Lopez, what types of work specifically decline in remote settings?", opts: ["Individual report writing and data analysis", "Collaborative creativity and complex problem-solving", "Customer service interactions and sales calls", "All categories of knowledge work equally"], ans: 1 },
      { q: "What financial benefit does Victor_T describe from working remotely?", opts: ["He received a significant salary increase", "His company pays for his home office equipment", "He saved money by moving to a more affordable city", "He no longer pays for work clothing or lunches"], ans: 2 },
      { q: "What problem does Elena_M describe observing among junior remote hires?", opts: ["They consistently missed project deadlines", "They struggled socially and professionally, with some feeling invisible and leaving", "They failed to respond to emails within appropriate timeframes", "They spent too much time on video calls rather than working independently"], ans: 1 },
      { q: "How do Victor_T and Elena_M's perspectives differ?", opts: ["Victor supports remote work and Elena supports in-person work for all employees equally", "Victor focuses on personal benefits, while Elena points out challenges remote work creates specifically for junior employees", "Both ultimately agree that hybrid work is the best solution", "Victor is a manager and Elena is a junior employee"], ans: 1 },
      { q: "The article implies advocates and critics evaluate remote work success using different criteria. What are those criteria?", opts: ["Salary and benefits vs. career advancement", "Measurable output and individual satisfaction vs. team dynamics and developmental experiences", "Short-term financial gains vs. long-term company growth", "Employee retention vs. customer satisfaction"], ans: 1 },
      { q: "The phrase 'co-located' in the second paragraph means:", opts: ["Sharing the same computer network", "Working in the same physical space", "Being hired by the same employer", "Located in adjacent cities"], ans: 1 }
    ]
  },
  {
    desc: "Read the article and the comments. Then, answer the questions.",
    time: 780,
    passage: `
      <div class="passage-header"><strong>Viewpoints: Should Canada Raise the Minimum Wage to $20 Per Hour Nationally?</strong></div>
      <p>The question of whether Canada should establish a universal federal minimum wage of twenty dollars per hour has intensified as the gap between living costs and earned income continues to widen for low-wage workers. Proponents argue that a higher minimum wage is not only a matter of economic fairness but a practical necessity. Research from the Canadian Centre for Policy Alternatives indicates that in most major Canadian cities, a single adult needs to earn at least twenty-two to twenty-five dollars per hour to cover basic necessities — housing, food, transportation, and healthcare. Supporters also point out that raising the minimum wage increases consumer spending, as low-wage earners typically spend most of their income in the local economy, creating a positive ripple effect for businesses.</p>
      <p>Opponents, including many small business associations and economic think tanks, argue that a steep minimum wage increase would accelerate automation, reduce total employment hours, and disproportionately harm small businesses that operate on narrow profit margins. Economist Samuel Davis warns that while large corporations can absorb higher labour costs, a corner bakery or family-run restaurant often cannot. "When labour costs jump, businesses face a binary choice: raise prices or cut hours. Either outcome harms the very workers the policy is designed to protect," Davis says. Critics also note that a single national minimum wage ignores vast regional differences in living costs — twenty dollars per hour provides very different purchasing power in rural New Brunswick compared to downtown Vancouver.</p>

      <div class="diagram-box">
        <strong>Comments:</strong><br><br>
        <strong>Anita_W:</strong> I've been working in retail for eleven years and I still can't afford a one-bedroom apartment without a roommate. This is not about luxury — it's about basic dignity. I am fully trained, experienced, and dependable, and I cannot live on what I earn. Something has to change.<br><br>
        <strong>Marcus_B:</strong> I own a sandwich shop with four employees. My margins are already under five percent. If the minimum wage goes to twenty dollars, I either raise my prices significantly or reduce everyone's hours. There's no magic money — it comes from somewhere, and that somewhere is usually the workers themselves or the customers.
      </div>
    `,
    questions: [
      { q: "According to the Canadian Centre for Policy Alternatives, how much does a single adult in most major Canadian cities need to cover basic necessities?", opts: ["At least fifteen dollars per hour", "At least eighteen dollars per hour", "At least twenty-two to twenty-five dollars per hour", "At least thirty dollars per hour"], ans: 2 },
      { q: "Why do supporters say raising the minimum wage benefits local businesses?", opts: ["Higher wages reduce employee turnover and training costs", "Low-wage earners tend to spend most of their income locally, stimulating the economy", "It attracts higher-skilled workers to the region", "The government provides subsidies to businesses when wages increase"], ans: 1 },
      { q: "What does economist Samuel Davis warn will happen to small businesses when labour costs increase?", opts: ["They will move their operations overseas", "They will be forced to merge with larger corporations", "They will raise prices or cut hours, harming the workers the policy targets", "They will apply for government bailouts"], ans: 2 },
      { q: "What criticism is raised about applying a single national minimum wage across Canada?", opts: ["It creates unfair competition between provinces", "Twenty dollars per hour would be too low in all provinces", "Regional cost-of-living differences mean the same wage has different real values in different areas", "A national minimum wage would violate provincial jurisdiction"], ans: 2 },
      { q: "What is Anita_W's main point in her comment?", opts: ["Retail workers should be given company stock instead of higher wages", "After years of experience, she still cannot afford basic housing — it is a matter of dignity", "She believes the minimum wage is already sufficient", "Retail businesses should receive government support to pay higher wages"], ans: 1 },
      { q: "What does Marcus_B reveal about his business's financial situation?", opts: ["His profits have been growing steadily for years", "His margins are already very narrow, leaving little room for wage increases", "He has already automated most of his operations", "He supports the wage increase but cannot afford it"], ans: 1 },
      { q: "How do Anita_W and Marcus_B's perspectives illustrate the central tension in the debate?", opts: ["Anita represents the worker perspective of insufficient income; Marcus represents the small business perspective of financial constraints", "They both agree wages need to rise but disagree about the timeline", "Anita is focused on fairness while Marcus is concerned only about personal profit", "They represent urban and rural workers respectively"], ans: 0 },
      { q: "What does the article suggest about large corporations versus small businesses in relation to wage increases?", opts: ["Both are equally affected by minimum wage increases", "Large corporations actually benefit from minimum wage increases", "Large corporations can absorb higher labour costs more easily than small businesses", "Small businesses are protected by government grants when wages increase"], ans: 2 },
      { q: "The phrase 'narrow profit margins' in the second paragraph means:", opts: ["The business earns a very large amount of profit per sale", "The difference between revenue and expenses is very small", "The business is operating without proper accounting", "The business has limited physical space for its operations"], ans: 1 }
    ]
  },
  {
    desc: "Read the article and the comments. Then, answer the questions.",
    time: 780,
    passage: `
      <div class="passage-header"><strong>Viewpoints: Urban Green Spaces vs. Housing Development</strong></div>
      <p>As Canadian cities face intensifying housing affordability crises, municipal governments are increasingly under pressure to rezone and develop land traditionally preserved as public green space. Proponents of development argue that the housing shortage is itself a public health crisis — that families unable to afford housing, lengthy commutes, and overcrowded living conditions cause measurable harm to physical and mental well-being. In their view, using a portion of parkland to create thousands of affordable housing units is a reasonable trade-off. They also point out that well-designed mixed-use developments can include community gardens, rooftop terraces, and linear parks that partially replace the lost green space while dramatically increasing urban density.</p>
      <p>Opponents argue that green space in cities is not an aesthetic luxury but an essential component of urban health. Urban parks reduce ambient air temperatures in cities affected by the heat island effect, absorb stormwater that would otherwise overwhelm drainage systems, and provide documented mental health benefits for residents. Research from the University of Toronto found that having ten or more trees on a city block was associated with health improvements equivalent to earning seven thousand dollars more per year. Urban planning consultant Jessica Park warns that green space, once developed, is almost never recovered: "We can build more housing. We cannot build more mature urban forest. Once those trees and those ecosystems are gone, they are gone for generations."</p>

      <div class="diagram-box">
        <strong>Comments:</strong><br><br>
        <strong>Ryan_H:</strong> My family has been on the affordable housing waitlist for four years. My kids share one bedroom. Tell me that a park I can't afford to live near is more important than a home. I support building housing on every available lot in this city.<br><br>
        <strong>Priya_N:</strong> I live near one of the parks being proposed for development. On hot summer days, the temperature in the park is sometimes four or five degrees cooler than on the surrounding streets. That matters to elderly residents, kids, and people without air conditioning. Losing that green space would make this neighbourhood genuinely less livable.
      </div>
    `,
    questions: [
      { q: "What is the core tension explored in the article?", opts: ["Whether private developers or the government should build affordable housing", "The conflict between increasing housing supply and preserving urban green spaces", "Whether cities should prioritize environmental policy over economic development", "The debate over whether public parks should charge admission fees"], ans: 1 },
      { q: "How do housing development proponents justify building on parkland?", opts: ["Parkland provides no real benefit to urban residents", "The housing shortage causes real harm, and new developments can include alternative green features", "Urban trees can be transplanted to rural areas to compensate", "Green spaces are primarily used by wealthy residents"], ans: 1 },
      { q: "According to research from the University of Toronto, what health benefit is associated with having more urban trees?", opts: ["It reduces respiratory disease in children significantly", "Residents living near trees report better physical fitness", "The health improvements are equivalent to earning seven thousand dollars more annually", "Urban trees reduce the rate of depression by thirty percent"], ans: 2 },
      { q: "What warning does Jessica Park give about developing urban green spaces?", opts: ["The legal process for rezoning parkland takes decades", "Development will trigger protests that slow all other construction", "Green spaces, once lost, are not recovered for generations", "Developers typically overestimate the number of units they can build"], ans: 2 },
      { q: "What environmental function of urban parks is mentioned in the article?", opts: ["Producing organic food for surrounding communities", "Filtering groundwater that feeds municipal drinking supplies", "Reducing urban heat island temperatures and absorbing stormwater", "Providing habitat for endangered bird species"], ans: 2 },
      { q: "What is Ryan_H's main argument in his comment?", opts: ["Parks should be converted to temporary housing", "His family's urgent housing need makes the preservation of parkland feel like a lower priority", "He disagrees with the government's housing policy entirely", "Affordable housing should be built outside the city, not on parkland"], ans: 1 },
      { q: "What specific benefit of the park does Priya_N describe?", opts: ["It provides lower temperatures, making the neighbourhood more livable in summer heat", "It reduces crime rates in surrounding streets", "It is a significant source of local biodiversity", "It generates tourism revenue for the city"], ans: 0 },
      { q: "How do Ryan_H and Priya_N's viewpoints illustrate the difficulty of resolving this debate?", opts: ["Ryan is focused on future environmental impacts, while Priya is focused on current residents' needs", "Both ultimately prioritize the same outcomes but disagree on the method", "Ryan's immediate housing need and Priya's quality-of-life concerns are both legitimate and difficult to reconcile", "They represent opposing political parties rather than genuine personal perspectives"], ans: 2 },
      { q: "The term 'heat island effect' in the second paragraph refers to:", opts: ["A policy that reserves specific city blocks as heat-resilient zones", "The phenomenon where urban areas are significantly warmer than surrounding rural areas", "The practice of building glass-covered buildings that trap heat inside", "Seasonal temperature increases caused by industrial activity"], ans: 1 }
    ]
  }
];
